force-app/main/default/objects/FNS_AdminConfiguration__c/FNS_AdminConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Admin Configuration</label>
</CustomObject>

force-app/main/default/objects/FNS_AdminConfiguration__c/fields/FNS_RestrictedDispositionValues__c.field-meta.xml
<CustomField>
    <fullName>FNS_RestrictedDispositionValues__c</fullName>
    <label>Restricted Disposition Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountRole__c/FNS_FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <label>Product Role (NonFSC)</label>
    <nameField>
        <label>Product Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Roles (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountRole__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Product Roles (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <externalId>true</externalId>
    <label>CME Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FNS_ApplicationSelectorTest.cls
/**************************************************************************
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Test Class
* @description This test class is used for FNS_ApplicationSelector 
****************************************************************************/
@isTest
private class FNS_ApplicationSelectorTest { 
        
    public static Account accountRecord;   
    public static Opportunity  opportunityRecord;
    public static FNS_FinancialAccountRole__c roleRecord;
    public static FNS_FinancialAccount__c productRecord;  
    public static User user;
    
    @testSetup 
    static void testSetupMethod() {
        FNS_TestDataSetup testData = new FNS_TestDataSetup();
        user = testData.createUser('test@tes111.com');
        insert user;
        List<String> permissionSetNames = new List<String>(); 
        if(FNS_Util.isFSCInstalled){
            permissionSetNames.add('FNS_RelationshipManager_FSC');
        }
        permissionSetNames.add('FNS_RelationshipManager_NonFSC'); 
        
        List<PermissionSet> permissionList = testData.getPermissionSet(permissionSetNames); 
        
        List<PermissionSetAssignment> lstPSAssignments = new List<PermissionSetAssignment>();
        for(PermissionSet ps : permissionList){
            lstPSAssignments.add(new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id));
        }
        insert lstPSAssignments;
    }
    
    static void setup() {
        FNS_TestDataSetup test = new FNS_TestDataSetup();
        accountRecord = test.createAccount('TestAccount01');
        insert accountRecord;
        
        opportunityRecord = test.createOpportunityRecord(accountRecord.Id);
        insert opportunityRecord;
    }
    /**
    * @description: This Method is used to validate the selectById method.
    */ 
    static testMethod void selectByIdTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            Test.stopTest();
            List<Opportunity> oppList = new FNS_ApplicationSelector().selectById(new Set<Id>{opportunityRecord.Id});
            System.assertNotEquals(oppList, null);
        }
        
    }
    /**
    * @description: This Method is used to validate the selectApplicationById method.
    */ 
    static testMethod void selectApplicationByIdTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            Test.stopTest();
            List<Opportunity> oppList = new FNS_ApplicationSelector().selectApplicationById(new Set<Id>{opportunityRecord.Id});
            System.assertNotEquals(oppList, null);
        }
        
    }
    /**
    * @description: This Method is used to validate the selectPendingDealsWithTasks method.
    */ 
    static testMethod void selectPendingDealsWithTasksTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            Task taskRecord = new FNS_TestDataSetup().createTaskRecord(opportunityRecord.Id);
            insert taskRecord;
            Test.stopTest();
            
            List<Opportunity> oppList = new FNS_ApplicationSelector().selectPendingDealsWithTasks(new Set<Id>{opportunityRecord.Id}, true, UserInfo.getUserId(), false);
            System.assertNotEquals(oppList, null);
        }
    }
    /**
    * @description: This Method is used to validate the pendingDealsWithTasksByFilter method.
    */ 
    static testMethod void pendingDealsWithTasksByFilterTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            Task taskRecord = new FNS_TestDataSetup().createTaskRecord(opportunityRecord.Id);
            insert taskRecord;
            Test.stopTest();
            
            List<Opportunity> oppList = new FNS_ApplicationSelector().pendingDealsWithTasksByFilter(null, true, UserInfo.getUserId());
            System.assertNotEquals(oppList, null);
        }
    }
    /**
    * @description: This Method is used to validate the selectApplicationWithProducts method.
    */ 
    static testMethod void selectApplicationWithProductsTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            FNS_FinancialAccount__c productRecord = new FNS_TestDataSetup().createProductRecord(opportunityRecord.Id);
            insert productRecord;
            Test.stopTest();
            
            List<Opportunity> oppList = new FNS_ApplicationSelector().selectApplicationWithProducts(new Set<Id>{opportunityRecord.Id});
            System.assertNotEquals(oppList, null);
        }
    }
    /**
    * @description: This Method is used to validate the selectByApplicationtage method.
    */ 
    static testMethod void selectByApplicationtageTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            List<Opportunity> oppList = new FNS_ApplicationSelector().selectByApplicationtage('Proposal', UserInfo.getUserId());
            Test.stopTest();
            System.assertNotEquals(oppList, null);
            System.assertEquals(oppList[0].Id, opportunityRecord.Id);
        }
    }
    /**
    * @description: This Method is used to validate the getRestrictedDispositionValues method.
    */ 
    static testMethod void getRestrictedDispositionValuesTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            FNS_AdminConfiguration__c adminConfig = new FNS_AdminConfiguration__c();
            adminConfig.FNS_RestrictedDispositionValues__c = 'Proposal;Initial Input';
            insert adminConfig;
            
            Set<String> valueSet = new FNS_ApplicationSelector().getRestrictedDispositionValues();
                
            System.assertNotEquals(valueSet, null);
        }
    }
    /**
    * @description: This Method is used to validate the selectByExternalId method.
    */ 
    static testMethod void selectByExternalIdTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            List<Opportunity> oppList = new FNS_ApplicationSelector().selectByExternalId(new Set<String>{opportunityRecord.FNS_ApplicationExtId__c});
            System.assertNotEquals(oppList, null);
            Test.stopTest();
        }
    }
    /**
    * @description: This Method is used to validate the getApplicationId method.
    */ 
    static testMethod void getApplicationIdTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            List<Opportunity> oppList = new FNS_ApplicationSelector().getApplicationId((String)opportunityRecord.Id);
            
            System.assertNotEquals(oppList, null);
            Test.stopTest();
        }
    }
    /**
    * @description: This Method is used to validate the getApplicationRecordType method.
    */ 
    static testMethod void getApplicationRecordTypeTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            
            setup();
            Map<String, String> getApplicationRecordType = new FNS_ApplicationSelector().getApplicationRecordType(new Set<String>{opportunityRecord.Id});
            System.assertNotEquals(getApplicationRecordType, null);
            
            Test.stopTest();
            
        }
    }
}