force-app/main/default/objects/FNS_Activity__c/FNS_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity List</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ActivityExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityExternalId__c</fullName>
    <description>Activity Identifier</description>
    <externalId>true</externalId>
    <label>Activity External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ActivityNotes__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityNotes__c</fullName>
    <label>Activity Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_NextAvailableActivityIds__c.field-meta.xml
<CustomField>
    <fullName>FNS_NextAvailableActivityIds__c</fullName>
    <description>This field is to fetch all the available activities for this activity</description>
    <label>Next Available Activity Ids</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_NextDefaultActivityId__c.field-meta.xml
<CustomField>
    <fullName>FNS_NextDefaultActivityId__c</fullName>
    <description>This field is to identify what is the next activity for this activity</description>
    <label>Default Activity Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FNS_ActivitiesSelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on FNS_ActivitiesSelector
****************************************************************************************/
public with sharing class FNS_ActivitiesSelector extends fflib_SObjectSelector {
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are  
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param  
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/  
    public FNS_ActivitiesSelector() {
        super(true, true, true);
    }
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are  
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param  
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/  
    public FNS_ActivitiesSelector(Boolean enforceFLS) {
        super(true, true, false);
    }
    
    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of Custom Activity object
        * @param 	   none
        * @return      List of Schema.SObjectField of Custom Activity object
    **************************************************************************************/ 
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            FNS_Activity__c.Id,
            FNS_Activity__c.FNS_ActivityExternalId__c,
            FNS_Activity__c.FNS_Description__c, 
            FNS_Activity__c.FNS_NextAvailableActivityIds__c, 
            FNS_Activity__c.FNS_NextDefaultActivityId__c, 
            FNS_Activity__c.FNS_ActivityNotes__c, 
            FNS_Activity__c.FNS_SequenceNumber__c
        };
    }
    
    /*************************************************************************************
        * @description Method to return SObject type of Custom Activity object
        * @param 	   none
        * @return      Returns SObjecttype of Custom Activity object
    **************************************************************************************/ 
    public Schema.SObjectType getSObjectType() {
        return FNS_Activity__c.sObjectType;
    }
    
    /*************************************************************************************
        * @description Method to return Custom Activity records based on activityIds
        * @param 	   Set of Custom Activity ids
        * @return      Returns List of Custom Activity object
    **************************************************************************************/ 
    public List<FNS_Activity__c> selectById(Set<Id> activityIds) {
        return (List<FNS_Activity__c>) selectSObjectsById(activityIds);
    }
    
    /*************************************************************************************
        * @description Method to return Custom Activity records 
        * @param 	   none
        * @return      Returns List of Custom Activity object
    **************************************************************************************/ 
    public List<FNS_Activity__c> getAllActivities() {
        String baseNamespace = FNS_Util.getBasePackageNamepace();
        fflib_QueryFactory activitiesQueryFactory = newQueryFactory(true, true, true); 
        activitiesQueryFactory.setOrdering(baseNamespace+'FNS_SequenceNumber__c', fflib_QueryFactory.SortOrder.ASCENDING); 
        return (List<FNS_Activity__c>) Database.query(activitiesQueryFactory.toSOQL());
    }
    
    /*************************************************************************************
        * @description Method to return Custom Activity records based on activityIds
        * @param 	   Set of Custom Activity ids
        * @return      Returns List of Custom Activity object
    **************************************************************************************/ 
    public List<FNS_Activity__c> getActivitywithId(List<String> activityIds){
        String baseNamespace = FNS_Util.getBasePackageNamepace();
        fflib_QueryFactory activitiesQueryFactory = newQueryFactory(true, true, true);
        activitiesQueryFactory.assertIsAccessible();
        activitiesQueryFactory.setEnforceFLS(true);
        activitiesQueryFactory.selectField('Id');
        activitiesQueryFactory.selectField(baseNamespace+'FNS_ActivityExternalId__c');
        String activityQueryCondition; 
        if(activityIds != null){
             activityQueryCondition = baseNamespace +'FNS_ActivityExternalId__c IN :activityIds AND ' + baseNamespace +'FNS_ActivityExternalId__c != null'; 
             activitiesQueryFactory.setCondition(activityQueryCondition);
        }
        return (List<FNS_Activity__c>) Database.query(activitiesQueryFactory.toSOQL());
    }
    
}