force-app/main/default/objects/FNS_Activity__c/FNS_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity List</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Bank__c/FNS_Bank__c.object-meta.xml
<CustomObject>
    <description>Start Date</description>
    <label>Bank</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ConfigurationType__c/FNS_ConfigurationType__c.object-meta.xml
<CustomObject>
    <label>Configuration Type</label>
    <nameField>
        <label>Configuration Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ConfigurationType__c/fields/FNS_ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ConfigurationType__c</fullName>
    <label>Configuration Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FeeType__c/FNS_FeeType__c.object-meta.xml
<CustomObject>
    <label>Fee Type</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Fee Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FeeType__c/recordTypes/FNS_FeeType.recordType-meta.xml
<RecordType>
    <fullName>FNS_FeeType</fullName>
    <active>true</active>
    <label>Fee Type</label>
</RecordType>

force-app/main/default/objects/FNS_ProcessCenter__c/FNS_ProcessCenter__c.object-meta.xml
<CustomObject>
    <label>Process Center</label>
    <nameField>
        <label>Process Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProcessGroup__c/FNS_ProcessGroup__c.object-meta.xml
<CustomObject>
    <label>Process Group</label>
    <nameField>
        <label>Process Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProductType__c/FNS_ProductType__c.object-meta.xml
<CustomObject>
    <label>Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProductType__c/recordTypes/FNS_ProductType.recordType-meta.xml
<RecordType>
    <fullName>FNS_ProductType</fullName>
    <active>true</active>
    <label>Product Type</label>
</RecordType>

force-app/main/default/classes/FNS_RefreshDataFromCMEController.cls
/**************************************************************************
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Component Controller
* @description Helps in updating records in SFDC from FFDC using Config API calls
****************************************************************************/
public with sharing class FNS_RefreshDataFromCMEController {
    /***********************************************************************
    * @description This methods updates FNS_Activity__c object records from FFDC 
    * @param none
    * @return String
    ************************************************************************/
    @AuraEnabled
    public static Object refreshActivities() {
        return FNS_WorkflowConfigurationsDomain.getConfigurations();
    }
    
    /***********************************************************************
    * @description This methods updates FNS_Bank__c object records from FFDC 
    * @param none
    * @return String
    ************************************************************************/
    @AuraEnabled
    public static Object refreshBankDomains() {
        return FNS_BankDomain.getConfigurations();
    }
    
    /***********************************************************************
    * @description This methods updates FNS_FeeType__c object records from FFDC 
    * @param none
    * @return String
    ************************************************************************/
    @AuraEnabled
    public static Object refreshFeeTypes() {
        //return FNS_FeeTypeDomain.getConfigurations();
        return FNS_FeeType.getConfigurations();
    }
    
    /***********************************************************************
    * @description This methods updates FNS_ProcessCenter__c object records from FFDC 
    * @param none
    * @return String
    ************************************************************************/
    @AuraEnabled
    public static Object refreshProcessCenterDomain() {
        return FNS_ProcessCenterDomain.getConfigurations();
    }
    
    /***********************************************************************
    * @description This methods updates FNS_ProcessGroup__c object records from FFDC 
    * @param none
    * @return String
    ************************************************************************/
    @AuraEnabled
    public static Object refreshProcessGroup() {
        return FNS_ProcessGroupDomain.getConfigurations();
    }
    
    /***********************************************************************
    * @description This methods updates FNS_ProductType__c object records from FFDC 
    * @param none
    * @return String
    ************************************************************************/
    @AuraEnabled
    public static Object refreshProductType() {
        // return FNS_ProductTypeDomain.getConfigurations();
           return FNS_ProductType.getConfigurations();
    }

    /***********************************************************************
    * @description This methods updates FNS_ConfigurationType__c object records from FFDC 
    * @param none
    * @return String
    ************************************************************************/
    @AuraEnabled
    public static Object refreshConfigurationType() {
        return FNS_ConfigurationDomain.getConfigurations();
    } 
    /***********************************************************************
    * @description This methods updates picklist values to Record Types 
    * @param none
    * @return none
    ************************************************************************/
     @AuraEnabled
    public static void scheduleRecordTypeUpdate(){
         //new FNS_ConfigurationDomain().updateCountryPurpose();
           List<String> configList = New List<String>{'Structure','ConfigCurrency','TrackingItemStatus','State','Disposition','Role','FeeType','ProductType','DocumentPriority','PricingType','Frequency','Purpose','PaymentType','ContactType','Province','Country'};
           for(String str : configList  )
           {
             List <String> config = new List<String>();
             config.add(str);
             FNS_RecordTypeUpdate.UpdateRecordType(config);
        
          } 
    }
}