force-app/main/default/objects/FNS_SFDCFFDCSetup__c/FNS_SFDCFFDCSetup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Defines SFDC to FFDC configuration parameters.</description>
    <label>SFDC-FFDC Setup</label>
</CustomObject>

force-app/main/default/objects/FNS_SFDCFFDCSetup__c/fields/FNS_AccessTokenUrl__c.field-meta.xml
<CustomField>
    <fullName>FNS_AccessTokenUrl__c</fullName>
    <label>Access Token Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FNS_SFDCFFDCSetup__c/fields/FNS_ConsumerSecret__c.field-meta.xml
<CustomField>
    <fullName>FNS_ConsumerSecret__c</fullName>
    <label>Consumer Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FNS_SFDCToFFDCSelectorTest.cls
/***************************************************************************************
* @description Class This test class is used for FNS_SFDCToFFDCSelector
* @author Swanand Mulay
* @date 04/29/2019
* @Support Email swanandm@comitydesigns.com
****************************************************************************************/
@isTest
public class FNS_SFDCToFFDCSelectorTest {
  
    public static FNS_SFDCFFDCSetup__c  setupObject;
    public static List<FNS_SFDCFFDCSetup__c>  setupObjRecordList;
    
    static void setup() {
        
        FNS_SFDCFFDCSetup__c setupObject = new FNS_SFDCFFDCSetup__c();
        setupObject.FNS_ConsumerKey__c = 'Test Consumer Key';
        setupObject.FNS_ConsumerSecret__c = 'Test Consumer Secret';
        setupObject.FNS_AccessTokenUrl__c = 'Test Access Token';
        setupObject.FNS_OrganisationId__c = 'Test Org Id';
        
        insert setupObject;
        
    }
    static testMethod void getAllRecords() {
        Test.startTest();
        setup();
        Test.stopTest();
        new FNS_SFDCToFFDCSelector(true);
        List<FNS_SFDCFFDCSetup__c> sfdctoFfdcRecordList = new FNS_SFDCToFFDCSelector().getAllRecords();
        System.assertNotEquals(sfdctoFfdcRecordList, null);
    }
}