force-app/main/default/objects/FNS_ProductType__c/FNS_ProductType__c.object-meta.xml
<CustomObject>
    <label>Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProductType__c/fields/FNS_Description__c.field-meta.xml
<CustomField>
    <fullName>FNS_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProductType__c/fields/FNS_DMLType__c.field-meta.xml
<CustomField>
    <fullName>FNS_DMLType__c</fullName>
    <label>DML Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FNS_ProductTypeTriggerHandler.cls
/*****************************************************************************************
* @description Config Trigger handler for record operations
* @author keerthi
* @date Apr 22 2019
* @Support Email keerthi@comitydesigns.com
******************************************************************************************/
public with sharing class FNS_ProductTypeTriggerHandler extends fflib_SObjectDomain {
    
    /********************************************************************************************************
    * @description  Interface used by the triggerHandler in constructing instances of TriggerHandler class 
    * @Params       none
    * @Returns      none
    * @author       keerthi@comitydesigns.com
    *********************************************************************************************************/

    public FNS_ProductTypeTriggerHandler(List<FNS_ProductType__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new FNS_ProductTypeTriggerHandler(sObjectList);
        }
    }
    
    public override void onBeforeInsert() {
        if(Trigger.isInsert){            
            for(FNS_ProductType__c configInsert : (List<FNS_ProductType__c>)Trigger.New){
                configInsert.FNS_DMLType__c = FNS_Constants.CONFIG_DMLTYPE_INSERT;
            }
        }        
    }

    public override void onBeforeUpdate(Map<Id,SObject> existingRecords) {
        if(Trigger.isUpdate){            
            for(FNS_ProductType__c configUpdate : (List<FNS_ProductType__c>)Records){
                FNS_ProductType__c configValue = (FNS_ProductType__c)Trigger.oldMap.get(configUpdate.Id);
                if(!configValue.FNS_Description__c.equalsIgnoreCase(configUpdate.FNS_Description__c)){
                    configUpdate.FNS_DMLType__c = FNS_Constants.CONFIG_DMLTYPE_UPDATE;
                }
            }
        }
    }

    public override void onAfterInsert(){
        List<FNS_ProductType__c> configInsertList = new List<FNS_ProductType__c>();
        if(Trigger.isInsert){  
            for(FNS_ProductType__c configInsert : (List<FNS_ProductType__c>)Trigger.New){
                configInsertList.add(configInsert);
            }
        }
        if(!configInsertList.isEmpty()){
            FNS_ProductTypeDomain.insertInGlobalPicklist(configInsertList);
        }
    }

    public override void onAfterUpdate(Map<Id,SObject> existingRecords) { 
        List<FNS_ProductType__c> configUpdateList = new List<FNS_ProductType__c>();
        if(Trigger.isUpdate){            
            for(FNS_ProductType__c configUpdate : (List<FNS_ProductType__c>)Records){
                configUpdateList.add(configUpdate);
            }
        }
        if(!configUpdateList.isEmpty()){
            FNS_ProductTypeDomain.updateInGlobalPicklist(configUpdateList);
        }
    }

    
}