force-app/main/default/objects/FNS_SFDCFFDCConnection__mdt/FNS_SFDCFFDCConnection__mdt.object-meta.xml
<CustomObject>
    <label>SFDC-FFDC Connection</label>
    <pluralLabel>FNS_SFDCFFDCConnection</pluralLabel>
</CustomObject>

force-app/main/default/objects/FNS_SFDCFFDCConnection__mdt/fields/FNS_ConsumerKey__c.field-meta.xml
<CustomField>
    <fullName>FNS_ConsumerKey__c</fullName>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_SFDCFFDCConnection__mdt/fields/FNS_ConsumerSecret__c.field-meta.xml
<CustomField>
    <fullName>FNS_ConsumerSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_SFDCFFDCConnection__mdt/fields/FNS_EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>FNS_EndPointURL__c</fullName>
    <label>EndPoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FNS_FetchRefreshTokenBatchTest.cls
@isTest
public class FNS_FetchRefreshTokenBatchTest {
    
    static testMethod void FetchRefreshTokenBatch()
    {
        //FNS_SFDCFFDCConnection__mdt conRec = new FNS_SFDCFFDCConnection__mdt(FNS_Client_Id__c  = 'testIdtestststst', FNS_ClientSecret__c = 'testSecret' ,FNS_EndPointURL__c = 'testURL',FNS_GrantType__c = 'testGrant');
        //insert conRec;
        List<FNS_SFDCFFDCConnection__mdt> authRecordList = new FNS_SFDCFFDCConnectionSelector().selectRecordsByUserNames(new Set<String>{'Authorization'});
        for (FNS_SFDCFFDCConnection__mdt authObj :authRecordList){
            authObj.FNS_ConsumerKey__c='testId';
            authObj.FNS_ConsumerSecret__c='testSecret';
            authObj.FNS_EndPointURL__c='testEndPointUrl';
            //authObj.FNS_GrantType__c='TestGrantType';
        }
        Test.StartTest();
        FNS_FetchRefreshTokenBatch objBatch = new FNS_FetchRefreshTokenBatch();
        ID batchprocessid = Database.executeBatch(objBatch);
        Test.StopTest();
    }
}