force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Account__c.field-meta.xml
<CustomField>
    <fullName>FNS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Products</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Products</relationshipLabel>
    <relationshipName>AccountProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application</relationshipLabel>
    <relationshipName>FinancialAccountApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_EffectiveDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Effective Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_ExpiryDate__c</fullName>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_MaturityDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_MaturityDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Maturity Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_OriginationTypeIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_OriginationTypeIndicator__c</fullName>
    <label>Origination Type Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_RateType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateType__c</fullName>
    <label>Rate Type (Fixed or Variable)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_RiskType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RiskType__c</fullName>
    <label>Risk Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acceptances</fullName>
            </value>
            <value>
                <fullName>Acceptances Financing</fullName>
            </value>
            <value>
                <fullName>Acquisition loans</fullName>
            </value>
            <value>
                <fullName>Bankers Acceptance</fullName>
            </value>
            <value>
                <fullName>Bankers Acceptance (Sumitomo) SBLC NB</fullName>
            </value>
            <value>
                <fullName>Bills of Exchange</fullName>
            </value>
            <value>
                <fullName>Collateral</fullName>
            </value>
            <value>
                <fullName>Competitive Bids/Money Market Loans</fullName>
            </value>
            <value>
                <fullName>Current account</fullName>
            </value>
            <value>
                <fullName>Debt Instrument</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Discount Loans</fullName>
            </value>
            <value>
                <fullName>Escrow Deposit</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Guidance</fullName>
            </value>
            <value>
                <fullName>Intraday</fullName>
            </value>
            <value>
                <fullName>Letter of Credit - Standby Advised</fullName>
            </value>
            <value>
                <fullName>Letter of Credit - Trade</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Loans - Long Term</fullName>
            </value>
            <value>
                <fullName>Loans - Revolving</fullName>
            </value>
            <value>
                <fullName>Loans Construction</fullName>
            </value>
            <value>
                <fullName>Multi Currency Non-Loan</fullName>
            </value>
            <value>
                <fullName>Non-Loan Guaranty</fullName>
            </value>
            <value>
                <fullName>Repo Loans</fullName>
            </value>
            <value>
                <fullName>SBLC</fullName>
            </value>
            <value>
                <fullName>Swing Lines</fullName>
            </value>
            <value>
                <fullName>Warehouse Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Status__c.field-meta.xml
<CustomField>
    <fullName>FNS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Term__c.field-meta.xml
<CustomField>
    <fullName>FNS_Term__c</fullName>
    <label>Term</label>
    <required>true</required>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_TermUnit__c.field-meta.xml
<CustomField>
    <fullName>FNS_TermUnit__c</fullName>
    <label>Term Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Month</fullName>
            </value>
			<value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Account__c.field-meta.xml
<CustomField>
    <fullName>FNS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Loans</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Loans</relationshipLabel>
    <relationshipName>AccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Loan</relationshipLabel>
    <relationshipName>Financial_Account_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_EffectiveDate__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_ExpiryDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Loans (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccountTransactionExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransactionExtId__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_LoanProductType__c.field-meta.xml
<CustomField>
    <fullName>FNS_LoanProductType__c</fullName>
    <label>Loan Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_LoanPurpose__c.field-meta.xml
<CustomField>
   <fullName>FNS_LoanPurpose__c</fullName>
    <label>Loan Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Purpose</valueSetName>
    </valueSet>

</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_PricingFrequency__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingFrequency__c</fullName>
    <label>Pricing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_PricingType__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingType__c</fullName>
    <label>Pricing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_PricingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_RateType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateType__c</fullName>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
                <default>true</default>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_RequestedDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_RequestedDate__c</fullName>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Term__c.field-meta.xml
<CustomField>
    <fullName>FNS_Term__c</fullName>
    <label>Loan Term</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_TermUnit__c.field-meta.xml
<CustomField>
    <fullName>FNS_TermUnit__c</fullName>
    <label>Term Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FNS_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_PricingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>PricingType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>ProductType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_LoansSelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on Loan object
****************************************************************************************/
public with sharing class FNS_LoansSelector extends fflib_SObjectSelector {
    
     /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/
    public FNS_LoansSelector() {
        super(true, true, true);
    }
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/
    public FNS_LoansSelector(Boolean enforceFLS) {
        super(true, true, false);
    }

    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of Loan object
        * @param 	   none
        * @return      List of Schema.SObjectField of Loan object
    **************************************************************************************/ 
    public List<Schema.SObjectField> getSObjectFieldList() {
        List<String> fieldList;
        Map<Schema.SObjectType,List<Schema.SObjectField>> fieldsMap = new Map<Schema.SObjectType,List<Schema.SObjectField>>();    	
        Map<String, List<String>> objectWithFieldsMap = new Map<String, List<String>>();    	
        String sobjectName;
        Schema.SObjectType sObj;
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        String extNamespace= FNS_Util.getExtensionPackageNamespace();
        String namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        if(FNS_Util.isFSCInstalled) {
            sobjectName = 'FinServ__FinancialAccountTransaction__c';
            fieldList = new List<String> {
                    namespace + 'FNS_Account__c',
                                'FinServ__FinancialAccount__c',
                                'FinServ__Amount__c',
                    namespace + 'FNS_EffectiveDate__c',
                    namespace + 'FNS_LoanSummary__c',
                    namespace + 'FNS_ExpiryDate__c',                  
                    namespace + 'FNS_FinancialAccountTransactionExtId__c',
                    namespace + 'FNS_LoanProductType__c',
                    namespace + 'FNS_LoanPurpose__c',
                    namespace + 'FNS_MaturityDate__c',
                    namespace + 'FNS_Application__c',
                    namespace + 'FNS_OriginationTypeIndicator__c',              
                    namespace + 'FNS_PricingFrequency__c',
                    namespace + 'FNS_PricingType__c',                    
                    namespace + 'FNS_RateType__c',
                    namespace + 'FNS_RequestedDate__c',
                    namespace + 'FNS_RiskType__c',
                    namespace + 'FNS_Term__c',
                    namespace + 'FNS_BypassValidation__c',
                    namespace + 'FNS_TermUnit__c'                   
                    };                        
        } 
        else {                            
            sobjectName = baseNamespace+'FNS_FinancialAccountTransaction__c';
                fieldList = new List<String> {
                    'Id',
                    namespace + 'FNS_Account__c',
                    namespace + 'FNS_Amount__c',
                    namespace + 'FNS_EffectiveDate__c',
                    namespace + 'FNS_LoanSummary__c', 
                    namespace + 'FNS_FinancialAccountTransactionExtId__c',                    
                    namespace + 'FNS_ExpiryDate__c',
                    namespace + 'FNS_FinancialAccount__c',
                    namespace + 'FNS_RateType__c',                    
                    namespace + 'FNS_LoanProductType__c',
                    namespace + 'FNS_LoanPurpose__c',
                    namespace + 'FNS_MaturityDate__c',
                    namespace + 'FNS_Application__c',
                    namespace + 'FNS_OriginationTypeIndicator__c',                   
                    namespace + 'FNS_PricingFrequency__c',
                    namespace + 'FNS_PricingType__c',               
                    namespace + 'FNS_RequestedDate__c',                   
                    namespace + 'FNS_RiskType__c',
                    namespace + 'FNS_Status__c',
                    namespace + 'FNS_Term__c',
                    namespace + 'FNS_BypassValidation__c',
                    namespace + 'FNS_TermUnit__c'                  
                };                            
        }
        fieldList.add('Name');
        objectWithFieldsMap.put(sobjectName, fieldList);										  
        fieldsMap = FNS_Util.getSobjectWithFields(objectWithFieldsMap);
        sobj = Schema.getGlobalDescribe().get(sobjectName);
        return  fieldsMap.get(sobj);
    }
    
    /*************************************************************************************
        * @description Method to return SObject type of Loan object
        * @param 	   none
        * @return      Returns SObjecttype of Loan object
    **************************************************************************************/ 
    public Schema.SObjectType getSObjectType() {
        String finAccountObjName;
        string baseNamespace= FNS_Util.getBasePackageNamepace();
        string extNamespace= FNS_Util.getExtensionPackageNamespace();
        string namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        if(FNS_Util.isFSCInstalled){
            finAccountObjName = 'FinServ__FinancialAccountTransaction__c' ;
        }
        else {
            finAccountObjName = baseNamespace + 'FNS_FinancialAccountTransaction__c' ;
        }
        Schema.SObjectType finAccountObject = FNS_Util.getSobject(finAccountObjName);
        return finAccountObject;
    }
    
    /*************************************************************************************
        * @description Method to return List of Sobject
        * @param 	   none
        * @return      Returns List of Loan object
    **************************************************************************************/ 
    public List<Sobject> getAllProducts() {
        return Database.query(newQueryFactory().toSOQL());
    }
    
    /*************************************************************************************
        * @description Method to return List of sobject records
        * @param 	   Number of Loans
        * @param 	   Operator
        * @return      Returns List of Loan object
    **************************************************************************************/ 
    public List<Sobject> getLoanDetailsWithFilter(Integer numberOFLoan, String operator) {
        String queryString;
    	String objectName;
        String baseNamespace= FNS_Util.getBasePackageNamepace();
    	if(FNS_Util.isFSCInstalled){
    		objectName = 'FinServ__FinancialAccountTransaction__c';
    	} 
        else{
    		 objectName = baseNamespace+'FNS_FinancialAccountTransaction__c';
    	}
        queryString = 'SELECT '+baseNamespace+'FNS_Application__c,count(ID) oppCount FROM '+  String.escapeSingleQuotes(objectName) + ' group by '+baseNamespace+'FNS_Application__c having count(ID) ' + operator  +' ' + numberOFLoan + ' Limit 1000';
        FNS_ObjectAccessContainer.checkFinAccountTransactionAccess(FNS_AccessController.DML_OPERATION_READ);
        List<sObject> loanList = Database.query(queryString); 
        return loanList;
    }

    /*************************************************************************************
        * @description Method to return List of Sobject based on productIds
        * @param 	   Set of Product ids
        * @return      Returns List of loan object
    **************************************************************************************/ 
    public List<SObject> getLoans(Set<Id> productIds) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        String extNamespace= FNS_Util.getExtensionPackageNamespace();
        String namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        String loanQueryCondition = '';
        fflib_QueryFactory loanQueryFactory = newQueryFactory(true, true, true);
        loanQueryFactory.assertIsAccessible();
        loanQueryFactory.setEnforceFLS(true);
        List<String> loanQueryConditions = new List<String>();
        if(FNS_Util.isFSCInstalled){
            loanQueryCondition = 'FinServ__FinancialAccount__c IN : productIds';
        }else {
            loanQueryCondition = namespace + 'FNS_FinancialAccount__c IN : productIds';
        }
        loanQueryConditions.add(loanQueryCondition);
        if(! loanQueryConditions.isEmpty()){
            loanQueryFactory.setCondition(String.join(loanQueryConditions, ' AND '));
        }
        return (List<SObject>) Database.query(loanQueryFactory.toSOQL());
    }
    
    /*************************************************************************************
        * @description Method to return List of Sobject based on List of Loan Ids
        * @param 	   List of loan Ids
        * @return      Returns List of Loan object
    **************************************************************************************/ 
    public List<SObject> selectLoanName(List<String> loanIds) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        String extNamespace= FNS_Util.getExtensionPackageNamespace();
        String namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        fflib_QueryFactory loansQueryFactory = newQueryFactory(true, true, true); 
        loansQueryFactory.assertIsAccessible();
        loansQueryFactory.setEnforceFLS(true);
        loansQueryFactory.selectField('Id'); 
        loansQueryFactory.selectField(namespace+'FNS_FinancialAccountTransactionExtId__c');
        String loansQueryCondition;
        if(loanIds != null){
            loansQueryCondition = namespace+'FNS_FinancialAccountTransactionExtId__c IN :loanIds';
            loansQueryFactory.setCondition(loansQueryCondition);
        }
        fflib_SObjectSelector accountSelector = new FNS_AccountSelector();
        accountSelector.configureQueryFactoryFields(loansQueryFactory, namespace+'FNS_Account__r');
        fflib_SObjectSelector productSelector = new FNS_ProductsSelector();
        if(FNS_Util.isFSCInstalled){
            productSelector.configureQueryFactoryFields(loansQueryFactory, 'FinServ__FinancialAccount__r');
        }
        else{
            productSelector.configureQueryFactoryFields(loansQueryFactory, namespace+'FNS_FinancialAccount__r');
        }
        loansQueryFactory.setLimit(5); // to be updated later based as response 
        return (List<SObject>) Database.query(loansQueryFactory.toSOQL());
    }
}