force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Pricing__c/FNS_Pricing__c.object-meta.xml
<CustomObject>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
 	<displayFormat>PN -{0000}</displayFormat>     
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Product</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Pricings</relationshipLabel>
    <relationshipName>FinancialProductPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FNS_PricingSelectorTest.cls
/**************************************************************************
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Test Class
* @description This test class is used for FNS_PricingSelector
****************************************************************************/
@isTest
private class FNS_PricingSelectorTest { 
    public static FNS_Pricing__c pricingRecord;
    public static FNS_FinancialAccount__c productRecord;    
    public static Opportunity  opportunityRecord;    
    public static Account accountRecord;   
    public static User user;
	
	@testSetup 
    static void testSetupMethod() {
        FNS_TestDataSetup testData = new FNS_TestDataSetup();
        user = testData.createUser('test@tes111.com');
        insert user;
        List<String> permissionSetNames = new List<String>(); 
        if(FNS_Util.isFSCInstalled){
            permissionSetNames.add('FNS_RelationshipManager_FSC');
        }
        permissionSetNames.add('FNS_RelationshipManager_NonFSC'); 
        
        List<PermissionSet> permissionList = testData.getPermissionSet(permissionSetNames); 
        
        List<PermissionSetAssignment> lstPSAssignments = new List<PermissionSetAssignment>();
        for(PermissionSet ps : permissionList){
            lstPSAssignments.add(new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id));
        }
        insert lstPSAssignments; 
    }
    
    static void setup() {
        FNS_TestDataSetup test = new FNS_TestDataSetup();
        
        accountRecord = test.createAccount('TestAccount01');
        insert accountRecord;
        opportunityRecord = test.createOpportunityRecord(accountRecord.Id);
        insert opportunityRecord;
        productRecord = test.createProductRecord(opportunityRecord.Id);
        insert productRecord;
        pricingRecord = test.createPricingRecord(productRecord.Id);
        insert pricingRecord;
    }
    static testMethod void selectByIdTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            List<FNS_Pricing__c> pricingRecordsById =  new FNS_PricingSelector().selectById(new SET<Id>{pricingRecord.Id});
            System.assertNotEquals(pricingRecordsById, null);
            Test.stopTest();
        }
    }
    static testMethod void getPricingsTest() {
        User usr = [Select id from User where Username ='test@tes111.com'];
        
        System.runAs(usr){
            Test.startTest();
            setup();
            List<FNS_Pricing__c> pricingRecords =  new FNS_PricingSelector().getPricings(new SET<Id>{productRecord.Id});
            System.assertNotEquals(pricingRecords, null);
            Test.stopTest();
        }
    }
}