force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Loans (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/FNS_PredictiveAnalytics__c.object-meta.xml
<CustomObject>
    <label>Predictive Analytics</label>
    <nameField>
        <label>Predictive Analytics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predictive Analytics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_Customer__c.field-meta.xml
<CustomField>
    <fullName>FNS_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Predictive Analytics</relationshipLabel>
    <relationshipName>CustomerPredictiveAnalytics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_CustomerName__c.field-meta.xml
<CustomField>
    <fullName>FNS_CustomerName__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Predictive Analytic Product</relationshipLabel>
    <relationshipName>PredictiveAnalyticProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_FinancialAccountName__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountName__c</fullName>
    <label>Facility Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan</relationshipLabel>
    <relationshipName>Loan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_FinancialAccountTransactionName__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransactionName__c</fullName>
    <label>Loan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_Recommendation__c.field-meta.xml
<CustomField>
    <fullName>FNS_Recommendation__c</fullName>
    <label>Recommendation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_PredictiveAnalytics__c/fields/FNS_RecommendationDescription__c.field-meta.xml
<CustomField>
    <fullName>FNS_RecommendationDescription__c</fullName>
    <label>Recommendation Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/FNS_PredictiveAnalyticsController.cls
/************************************************************************************
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Predictive Analytics- Home Page
* @description This class is server side controller to do all DML operation for Predictive analytics component  
****************************************************************************************/
public with sharing class FNS_PredictiveAnalyticsController {
    
    public static FNS_ErrorLog logger = new FNS_ErrorLog();
    
    /***********************************************************************************
* @description Method to get All Records 
* @Params      null
* @Returns    Returns ListWrapper as String
***********************************************************************************/ 
    @AuraEnabled
    public static Object getRecords(){
        Map<String, Object> objValue = new Map<String, Object> {
            FNS_Constants.API_RESPONSE => FNS_Constants.API_EMPTY,
            FNS_Constants.API_ERROR => FNS_Constants.API_EMPTY
            };
                    string baseNamespace= FNS_Util.getBasePackageNamepace();
        string extNamespace= FNS_Util.getExtensionPackageNamespace();
        string namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        
        List<FNS_PredictiveAnalytics__c> predAnalyticslist;
        List<PredictiveAnalyticsWrapper> listWrapper = new List<PredictiveAnalyticsWrapper>(); 
        
        try{
            FNS_PredictiveAnalyticsSelector predicAnalyticsSelector = new FNS_PredictiveAnalyticsSelector();
            predAnalyticslist = predicAnalyticsSelector.getPredictiveAnalytics();
            for(FNS_PredictiveAnalytics__c pred: predAnalyticslist ){
                PredictiveAnalyticsWrapper wrap = new PredictiveAnalyticsWrapper(); 
                wrap.Id= (String)pred.get('Id');
                wrap.facilityName=  pred.FNS_FinancialAccountName__c;
                wrap.loanName=  pred.FNS_FinancialAccountTransactionName__c;
                wrap.recommendation=  pred.FNS_Recommendation__c;
                wrap.recommendationDescription =  pred.FNS_RecommendationDescription__c;
                wrap.CustomerId =  pred.FNS_Customer__c;
                wrap.CustomerName=  pred.FNS_CustomerName__c;
                if(FNS_Util.isFSCInstalled){
                    wrap.facilityId=  (String)pred.get(namespace+'FNS_FinancialAccountFSC__c');
                    wrap.loanId=  (String)pred.get(namespace+'FNS_FinancialAccountTransactionFSC__c');
                }
                else{
                    wrap.facilityId=  (String)pred.get(namespace+'FNS_FinancialAccount__c');
                    wrap.loanId=  (String)pred.get(namespace+'FNS_FinancialAccountTransaction__c');
                }
                listWrapper.add(wrap);
            }
            objValue.put(FNS_Constants.API_RESPONSE,JSON.serialize(listWrapper,true));
        }
        catch(Exception ex){
            logger.addLogRecord(namespace+'FNS_PredictiveAnalysisController', 'getListViews', ex.getMessage() + ex.getStackTraceString());
            objValue.put(FNS_Constants.API_ERROR,ex.getMessage());
        } 
        return objValue; 
    }
    
    /***********************************************************************************
* @description Method to get ListViews for PredictiveAnalytics 
* @Params      null
* @Returns     Returns List of ListViews 
***********************************************************************************/ 
    @AuraEnabled
    public static List<ListView> getListViews() {
        List<ListView> listviews; 
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        String extNamespace= FNS_Util.getExtensionPackageNamespace();
        String namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        
        String fieldSetName = '';
        
        if(FNS_Util.isFSCInstalled){
            fieldSetName = namespace+'FNS_PredictiveAnalyticsFSC';
        }else {
            fieldSetName = namespace+'FNS_PredictiveAnalytics';
        }
        try {
            listviews = new FNS_ListViewsSelector().selectByName(baseNamespace+'FNS_PredictiveAnalytics__c', new Set<String>{fieldSetName});
        } catch(Exception ex){
            logger.addLogRecord('FNS_PredictiveAnalysisController', 'getListViews', ex.getMessage() + ex.getStackTraceString());
        }    
        return listviews;
    }
    
    /*************************************************************************************
* @description  Wrapper to return for getRecords method 
* @Params       none
* @Returns      none
**************************************************************************************/
    public with sharing class PredictiveAnalyticsWrapper{
        String Id; 
        String FacilityId; 
        String FacilityName; 
        String Recommendation; 
        String RecommendationDescription; 
        String CustomerId; 
        String CustomerName; 
        String LoanId; 
        String LoanName; 
    }
}