force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_RateType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateType__c</fullName>
    <label>Rate Type (Fixed or Variable)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Loans (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_PricingType__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingType__c</fullName>
    <label>Pricing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_PricingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_RateType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateType__c</fullName>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
                <default>true</default>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/FNS_Pricing__c.object-meta.xml
<CustomObject>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
 	<displayFormat>PN -{0000}</displayFormat>     
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_AllInRate__c.field-meta.xml
<CustomField>
    <fullName>FNS_AllInRate__c</fullName>
    <label>All In Rate</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_BaseRate__c.field-meta.xml
<CustomField>
    <fullName>FNS_BaseRate__c</fullName>
    <label>Base Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>FNS_BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_CalcType__c.field-meta.xml
<CustomField>
    <fullName>FNS_CalcType__c</fullName>
    <label>Calculation Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Product</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Pricings</relationshipLabel>
    <relationshipName>FinancialProductPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Pricings</relationshipLabel>
    <relationshipName>LoanPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>FNS_Frequencies__c</fullName>
    <label>Frequencies</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_PricingType__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingType__c</fullName>
    <label>Pricing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_PricingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_RateBasis__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateBasis__c</fullName>
    <label>Rate Basis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_RateType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateType__c</fullName>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Variable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_Spread__c.field-meta.xml
<CustomField>
    <fullName>FNS_Spread__c</fullName>
    <label>Spread</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/FNS_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_PricingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>PricingType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_PricingSelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on Custom object Pricing
****************************************************************************************/
public with sharing class FNS_PricingSelector extends fflib_SObjectSelector {
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/
    public FNS_PricingSelector() {
        super(true, true, true);
    }
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/
    public FNS_PricingSelector(Boolean enforceFLS) {
        super(true, true, false);
    }
    
    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of Custom object Pricing
        * @param 	   none
        * @return      List of Schema.SObjectField of Custom object Pricing
    **************************************************************************************/ 
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            FNS_Pricing__c.Id,
            FNS_Pricing__c.FNS_AllInRate__c,
            FNS_Pricing__c.FNS_BaseRate__c,
            FNS_Pricing__c.FNS_CalcType__c,
            FNS_Pricing__c.FNS_Frequencies__c,
            FNS_Pricing__c.FNS_FinancialAccount__c,
            FNS_Pricing__c.FNS_FinancialAccountTransaction__c,
            FNS_Pricing__c.FNS_PricingType__c,
            FNS_Pricing__c.FNS_RateBasis__c,
            FNS_Pricing__c.FNS_RateType__c,
            FNS_Pricing__c.FNS_BypassValidation__c,
            FNS_Pricing__c.FNS_Spread__c
        };
    }
    
    /*************************************************************************************
        * @description Method to return SObject type of Custom object Pricing
        * @param 	   none
        * @return      Returns SObjecttype of Custom object Pricing
    **************************************************************************************/ 
    public Schema.SObjectType getSObjectType() {
        return FNS_Pricing__c.sObjectType;
    }
    
    /*************************************************************************************
        * @description Method to return Custom Pricing records based on pricingIds
        * @param 	   Set of Pricing ids
        * @return      Returns List of Custom object Pricing
    **************************************************************************************/ 
    public List<FNS_Pricing__c> selectById(Set<Id> pricingIds) {
        return (List<FNS_Pricing__c>) selectSObjectsById(pricingIds);
    }
    
    /*************************************************************************************
        * @description Method to return Custom Pricing records based on productIds
        * @param 	   Set of Product Ids
        * @return      Returns List of Custom object Pricing
    **************************************************************************************/ 
    public List<FNS_Pricing__c> getPricings(Set<Id> productIds) {
        fflib_QueryFactory pricingQueryFactory = newQueryFactory(true, true, true);
        pricingQueryFactory.assertIsAccessible();
        pricingQueryFactory.setEnforceFLS(true);
        String pricingQueryCondition = '';
        List<String> pricingQueryConditions = new List<String>();
		
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        String extNamespace= FNS_Util.getExtensionPackageNamespace();
        String namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        
        if(productIds != null){
            if(FNS_Util.isFSCInstalled){
            	pricingQueryCondition = extNamespace + 'FNS_FinancialAccountFSC__c IN : productIds';
            }else {
            	pricingQueryCondition = baseNamespace + 'FNS_FinancialAccount__c IN : productIds';
            }
        }
        pricingQueryConditions.add(pricingQueryCondition);
        if(! pricingQueryConditions.isEmpty()){
            pricingQueryFactory.setCondition(String.join(pricingQueryConditions, ' AND '));
        }
		
        return (List<FNS_Pricing__c>) Database.query(pricingQueryFactory.toSOQL());
    }
}