force-app/main/default/objects/FNS_ErrorLog__c/FNS_ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ErrorLog__c/fields/FNS_ApexClass__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ErrorLog__c/fields/FNS_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>FNS_ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FNS_ErrorLog__c/fields/FNS_Method__c.field-meta.xml
<CustomField>
    <fullName>FNS_Method__c</fullName>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FNS_ErrorLog.cls
/*****************************************************************************************
 * Copyright (c) 2019, Brillio
 * All rights reserved.
 * @author Brillio
 * @date 2019
 * @group Access Handler
 * @description Class is used to insert all errors in Error Log object.
 ******************************************************************************************/
public with sharing class FNS_ErrorLog {

	/*************************************************************************************
	 * @description  Method to insert error record based on apex class, method and error message.
	 * @Params       Name of apex class
	 * @Params       Name of Method
	 * @Params       Error message
	 * @Returns      none
	 *************************************************************************************/
	public void addLogRecord(String apexClass, String methodName, String errorMsg){
		// Set up the unit of work
		fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
				new List<Schema.SObjectType>{
					FNS_ErrorLog__c.sObjectType
				}
		);

		FNS_ErrorLog__c errorLogRecord = new FNS_ErrorLog__c (
				FNS_ApexClass__c = apexClass,
				FNS_Method__c = methodName,
				FNS_ErrorMessage__c = errorMsg
		);

		uow.registerNew(errorLogRecord);
		FNS_ObjectAccessContainer.checkErrorLogAccess(FNS_AccessController.DML_OPERATION_INSERT);
		uow.commitWork();
	}
	
	public void addErrorLogList(List<FNS_ErrorLog__c> errorLogList){
		fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
				new List<Schema.SObjectType>{
					FNS_ErrorLog__c.sObjectType
				}
		);
		uow.registerNew(errorLogList);
		FNS_ObjectAccessContainer.checkErrorLogAccess(FNS_AccessController.DML_OPERATION_INSERT);
		uow.commitWork();
	}
}