force-app/main/default/objects/Account/recordTypes/FNS_Customer.recordType-meta.xml
<RecordType>
    <fullName>FNS_Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/FNS_Activity__c/FNS_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity List</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Activity__c/recordTypes/FNS_TrackingItem.recordType-meta.xml
<RecordType>
    <fullName>FNS_TrackingItem</fullName>
    <active>true</active>
    <label>Tracking Items</label>
</RecordType>

force-app/main/default/objects/FNS_Activity__c/recordTypes/FNS_TrackingItemReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_TrackingItemReadOnly</fullName>
    <active>true</active>
    <label>Tracking Items Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_Address__c/FNS_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Address__c/recordTypes/FNS_Address.recordType-meta.xml
<RecordType>
    <fullName>FNS_Address</fullName>
    <active>true</active>
    <label>Address</label>
</RecordType>

force-app/main/default/objects/FNS_Address__c/recordTypes/FNS_AddressReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_AddressReadOnly</fullName>
    <active>true</active>
    <label>Address Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/FNS_ApplicationWithOfficer__c.object-meta.xml
<CustomObject>
    <description>Application with Officer</description>
    <label>Application with Officer</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Application with Officer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application with Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/fields/FNS_Officer__c.field-meta.xml
<CustomField>
    <fullName>FNS_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Officer</description>
    <label>Officer</label>
    <referenceTo>FNS_Officer__c</referenceTo>
    <relationshipLabel>Application with Officers</relationshipLabel>
    <relationshipName>Application_with_Officers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/recordTypes/FNS_ApplicationWithOfficer.recordType-meta.xml
<RecordType>
    <fullName>FNS_ApplicationWithOfficer</fullName>
    <active>true</active>
    <label>Application with Officer</label>
</RecordType>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/recordTypes/FNS_ApplicationWithOfficerReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_ApplicationWithOfficerReadOnly</fullName>
    <active>true</active>
    <label>Application With Officer Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_Bank__c/FNS_Bank__c.object-meta.xml
<CustomObject>
    <description>Start Date</description>
    <label>Bank</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Bank__c/recordTypes/FNS_Bank.recordType-meta.xml
<RecordType>
    <fullName>FNS_Bank</fullName>
    <active>true</active>
    <label>Bank</label>
</RecordType>

force-app/main/default/objects/FNS_Bank__c/recordTypes/FNS_BankReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_BankReadOnly</fullName>
    <active>true</active>
    <label>Bank Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_CustomerProfile__c/FNS_CustomerProfile__c.object-meta.xml
<CustomObject>
    <description>Customer Profile</description>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Customer Profile No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_CustomerProfile__c/recordTypes/FNS_Customer.recordType-meta.xml
<RecordType>
    <fullName>FNS_Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/FNS_CustomerProfile__c/recordTypes/FNS_Customer_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>FNS_Customer_Read_Only</fullName>
    <active>true</active>
    <label>Customer Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_ErrorLog__c/FNS_ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Fee__c/FNS_Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FeeType__c.field-meta.xml
<CustomField>
    <fullName>FNS_FeeType__c</fullName>
    <label>Fee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_FeeType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facility</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>FinancialProductFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>LoanFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/recordTypes/FNS_Fee.recordType-meta.xml
<RecordType>
    <fullName>FNS_Fee</fullName>
    <active>true</active>
    <label>Fee</label>
</RecordType>

force-app/main/default/objects/FNS_Fee__c/recordTypes/FNS_FeeReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FeeReadOnly</fullName>
    <active>true</active>
    <label>Fee Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_FeeType__c/FNS_FeeType__c.object-meta.xml
<CustomObject>
    <label>Fee Type</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Fee Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FeeType__c/recordTypes/FNS_FeeType.recordType-meta.xml
<RecordType>
    <fullName>FNS_FeeType</fullName>
    <active>true</active>
    <label>Fee Type</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_ProductType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProductType__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/recordTypes/FNS_FinancialAccount.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccount</fullName>
    <active>true</active>
    <label>Financial Product</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccount__c/recordTypes/FNS_FinancialAccountReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountReadOnly</fullName>
    <active>true</active>
    <description>This record type will have only read only fields</description>
    <label>Financial Product Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountRole__c/FNS_FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <label>Product Role (NonFSC)</label>
    <nameField>
        <label>Product Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Roles (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountRole__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Product Roles (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountRole__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>Financial_Account_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountRole__c/recordTypes/FNS_FinancialAccountRole.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountRole</fullName>
    <active>true</active>
    <label>Financial Product Role</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountRole__c/recordTypes/FNS_FinancialAccountRoleReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountRoleReadOnly</fullName>
    <active>true</active>
    <label>Financial Product Role Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Loans (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_ProductType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProductType__c</fullName>
    <formula>TEXT(FNS_FinancialAccount__r.FNS_ProductType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/recordTypes/FNS_FinancialAccountTransaction.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountTransaction</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/recordTypes/FNS_FinancialAccountTransactionReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountTransactionReadOnly</fullName>
    <active>true</active>
    <label>Loan Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_Officer__c/FNS_Officer__c.object-meta.xml
<CustomObject>
    <label>Officer</label>
    <nameField>
        <label>Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Officer__c/recordTypes/FNS_Officer.recordType-meta.xml
<RecordType>
    <fullName>FNS_Officer</fullName>
    <active>true</active>
    <label>Officer</label>
</RecordType>

force-app/main/default/objects/FNS_Officer__c/recordTypes/FNS_Officer_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>FNS_Officer_Read_Only</fullName>
    <active>true</active>
    <label>Officer Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_Pricing__c/FNS_Pricing__c.object-meta.xml
<CustomObject>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
 	<displayFormat>PN -{0000}</displayFormat>     
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Product</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Pricings</relationshipLabel>
    <relationshipName>FinancialProductPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Pricings</relationshipLabel>
    <relationshipName>LoanPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_RateIndex__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateIndex__c</fullName>
    <label>Rate Index</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/recordTypes/FNS_Pricing.recordType-meta.xml
<RecordType>
    <fullName>FNS_Pricing</fullName>
    <active>true</active>
    <label>Pricing</label>
</RecordType>

force-app/main/default/objects/FNS_Pricing__c/recordTypes/FNS_PricingReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_PricingReadOnly</fullName>
    <active>true</active>
    <label>Pricing Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_ProcessCenter__c/FNS_ProcessCenter__c.object-meta.xml
<CustomObject>
    <label>Process Center</label>
    <nameField>
        <label>Process Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProcessCenter__c/recordTypes/FNS_ProcessCenter.recordType-meta.xml
<RecordType>
    <fullName>FNS_ProcessCenter</fullName>
    <active>true</active>
    <label>Process Center</label>
</RecordType>

force-app/main/default/objects/FNS_ProcessGroup__c/FNS_ProcessGroup__c.object-meta.xml
<CustomObject>
    <label>Process Group</label>
    <nameField>
        <label>Process Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProcessGroup__c/recordTypes/FNS_ProcessGroup.recordType-meta.xml
<RecordType>
    <fullName>FNS_ProcessGroup</fullName>
    <active>true</active>
    <label>Process Group</label>
</RecordType>

force-app/main/default/objects/FNS_ProductType__c/FNS_ProductType__c.object-meta.xml
<CustomObject>
    <label>Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProductType__c/recordTypes/FNS_ProductType.recordType-meta.xml
<RecordType>
    <fullName>FNS_ProductType</fullName>
    <active>true</active>
    <label>Product Type</label>
</RecordType>

force-app/main/default/objects/FNS_RateIndex__c/FNS_RateIndex__c.object-meta.xml
<CustomObject>
    <label>Rate Index</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Rate Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_RateIndex__c/recordTypes/FNS_RateIndex.recordType-meta.xml
<RecordType>
    <fullName>FNS_RateIndex</fullName>
    <active>true</active>
    <label>Rate Index</label>
</RecordType>

force-app/main/default/objects/FNS_RelatedRoles__c/FNS_RelatedRoles__c.object-meta.xml
<CustomObject>
    <label>Application Roles</label>
    <nameField>
        <label>Application Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_TaxDetails__c/FNS_TaxDetails__c.object-meta.xml
<CustomObject>
    <label>Tax Details</label>
    <nameField>
        <label>Tax Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_TaxDetails__c/recordTypes/FNS_TaxDetails.recordType-meta.xml
<RecordType>
    <fullName>FNS_TaxDetails</fullName>
    <active>true</active>
    <label>Tax Details</label>
</RecordType>

force-app/main/default/objects/FNS_TaxDetails__c/recordTypes/FNS_TaxDetails_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>FNS_TaxDetails_Read_Only</fullName>
    <active>true</active>
    <label>FNS TaxDetails Read Only</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/FNS_Bank__c.field-meta.xml
<CustomField>
    <fullName>FNS_Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank</label>
    <referenceTo>FNS_Bank__c</referenceTo>
    <relationshipLabel>Application</relationshipLabel>
    <relationshipName>Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FNS_Application.recordType-meta.xml
<RecordType>
    <fullName>FNS_Application</fullName>
    <active>true</active>
    <businessProcess>FNS_ApplicationProcess</businessProcess>
    <description>Application Record Type</description>
    <label>Application</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/FNS_ApplicationReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_ApplicationReadOnly</fullName>
    <active>true</active>
    <businessProcess>FNS_ApplicationProcess</businessProcess>
    <label>Application Read Only</label>
</RecordType>

force-app/main/default/globalValueSets/FNS_FeeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>FeeType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>ProductType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_MappingLayoutConstant.cls
public with sharing class FNS_MappingLayoutConstant  {
    
    
    public static Map<String,String> mapRecTypeWithLayout ;
     
     public static Map<String,String> getmapping ()
     {
        mapRecTypeWithLayout  = new Map<String,String>();
     
         mapRecTypeWithLayout.put('Account.FNS_Customer' , 'Account-FNS Account Layout');
         mapRecTypeWithLayout.put('FNS_Activity__c.FNS_TrackingItem' , 'FNS_Activity__c-FNS Activity Layout');
         mapRecTypeWithLayout.put('FNS_Activity__c.FNS_TrackingItemReadOnly' , 'FNS_Activity__c-FNS Activity Read Only Layout');
         mapRecTypeWithLayout.put('FNS_Address__c.FNS_Address' , 'FNS_Address__c-FNS Address Layout');
         mapRecTypeWithLayout.put('FNS_Address__c.FNS_AddressReadOnly' , 'FNS_Address__c-FNS Address Read Only Layout');
         mapRecTypeWithLayout.put('FNS_ApplicationWithOfficer__c.FNS_ApplicationWithOfficer' , 'FNS_ApplicationWithOfficer__c-FNS Application with Officer Layout');
         mapRecTypeWithLayout.put('FNS_ApplicationWithOfficer__c.FNS_ApplicationWithOfficerReadOnly' , 'FNS_ApplicationWithOfficer__c-FNS Application With Officer Read Only Layout');
         mapRecTypeWithLayout.put('FNS_Bank__c.FNS_Bank' , 'FNS_Bank__c-FNS Bank Layout');
         mapRecTypeWithLayout.put('FNS_Bank__c.FNS_BankReadOnly' , 'FNS_Bank__c-FNS Bank Read Only Layout');
         mapRecTypeWithLayout.put('FNS_CustomerProfile__c.FNS_Customer' , 'FNS_CustomerProfile__c-FNS Customer Profile Layout');
         mapRecTypeWithLayout.put('FNS_CustomerProfile__c.FNS_Customer_Read_Only' , 'FNS_CustomerProfile__c-FNS Customer Profile Read Only Layout');
         //mapRecTypeWithLayout.put('FNS_ErrorLog__c.FNS_Bank' , 'FNS_ErrorLog__c-FNS Error Layout');    //FNS_ErrorLog__c object does not have record types.
         //mapRecTypeWithLayout.put('FNS_ErrorLog__c.FNS_Bank' , 'FNS_ErrorLog__c-FNS Error Read Only Layout');
         mapRecTypeWithLayout.put('FNS_FeeType__c.FNS_FeeType' , 'FNS_FeeType__c-FNS Fee Type Layout');
         mapRecTypeWithLayout.put('FNS_FeeType__c.FNS_FeeType' , 'FNS_FeeType__c-FNS Fee Type Read Only Layout');
         mapRecTypeWithLayout.put('FNS_Fee__c.FNS_Fee' , 'FNS_Fee__c-FNS Fee Layout');
         mapRecTypeWithLayout.put('FNS_Fee__c.FNS_FeeReadOnly' , 'FNS_Fee__c-FNS Fee Read Only Layout');    
         mapRecTypeWithLayout.put('FNS_FinancialAccountRole__c.FNS_FinancialAccountRole' , 'FNS_FinancialAccountRole__c-FNS Financial Account Role Layout');
         mapRecTypeWithLayout.put('FNS_FinancialAccountRole__c.FNS_FinancialAccountRoleReadOnly' , 'FNS_FinancialAccountRole__c-FNS Financial Account Role Read Only Layout');
         mapRecTypeWithLayout.put('FNS_FinancialAccountTransaction__c.FNS_FinancialAccountTransaction' , 'FNS_FinancialAccountTransaction__c-FNS Loan Layout');
         mapRecTypeWithLayout.put('FNS_FinancialAccountTransaction__c.FNS_FinancialAccountTransactionReadOnly' , 'FNS_FinancialAccountTransaction__c-FNS Loan Read Only Layout');      
         mapRecTypeWithLayout.put('FNS_FinancialAccount__c.FNS_FinancialAccount' , 'FNS_FinancialAccount__c-FNS Product Layout');
         mapRecTypeWithLayout.put('FNS_FinancialAccount__c.FNS_FinancialAccountReadOnly' , 'FNS_FinancialAccount__c-FNS Product Read Only Layout');    
         mapRecTypeWithLayout.put('FNS_Officer__c.FNS_Officer' , 'FNS_Officer__c-FNS Officer Layout');
         mapRecTypeWithLayout.put('FNS_Officer__c.FNS_Officer_Read_Only' , 'FNS_Officer__c-FNS Officer Read Only Layout');    
         mapRecTypeWithLayout.put('FNS_Pricing__c.FNS_Pricing' , 'FNS_Pricing__c-FNS Pricing Layout');
         mapRecTypeWithLayout.put('FNS_Pricing__c.FNS_PricingReadOnly' , 'FNS_Pricing__c-FNS Pricing Read Only Layout');    
         mapRecTypeWithLayout.put('FNS_ProcessCenter__c.FNS_ProcessCenter' , 'FNS_ProcessCenter__c-FNS ProcessCenter Layout');
         mapRecTypeWithLayout.put('FNS_ProcessCenter__c.FNS_ProcessCenter' , 'FNS_ProcessCenter__c-FNS ProcessCenter Read Only Layout'); 
         mapRecTypeWithLayout.put('FNS_ProcessGroup__c.FNS_ProcessGroup' , 'FNS_ProcessGroup__c-FNS Process Group Layout');
         mapRecTypeWithLayout.put('FNS_ProcessGroup__c.FNS_ProcessGroup' , 'FNS_ProcessGroup__c-FNS Process Group Read Only Layout');  
         mapRecTypeWithLayout.put('FNS_ProductType__c.FNS_ProductType' , 'FNS_ProductType__c-FNS Product Type Layout');
         mapRecTypeWithLayout.put('FNS_ProductType__c.FNS_ProductType' , 'FNS_ProductType__c-FNS Product Type Read Only Layout');  
         mapRecTypeWithLayout.put('FNS_RateIndex__c.FNS_RateIndex' , 'FNS_RateIndex__c-FNS Rate Index Layout');
         mapRecTypeWithLayout.put('FNS_RateIndex__c.FNS_RateIndex' , 'FNS_RateIndex__c-FNS Rate Index Read Only Layout');  
         mapRecTypeWithLayout.put('FNS_RelatedRoles__c.FNS_Related_Roles' , 'FNS_RelatedRoles__c-FNS Related Roles Layout');
         mapRecTypeWithLayout.put('FNS_RelatedRoles__c.FNS_Related_Roles_Read_Only' , 'FNS_RelatedRoles__c-FNS Related Roles Read Only Layout');         
         mapRecTypeWithLayout.put('FNS_TaxDetails__c.FNS_TaxDetails' , 'FNS_TaxDetails__c-FNS TaxDetails Layout');
         mapRecTypeWithLayout.put('FNS_TaxDetails__c.FNS_TaxDetails_Read_Only' , 'FNS_TaxDetails__c-FNS TaxDetails Read Only Layout');  
         mapRecTypeWithLayout.put('Lead.FNS_Lead' , 'Lead-FNS Lead Layout');
         mapRecTypeWithLayout.put('Opportunity.FNS_Application' , 'Opportunity-FNS ApplicationLayout');  
         mapRecTypeWithLayout.put('Opportunity.FNS_ApplicationReadOnly' , 'Opportunity-FNS ApplicationReadOnlyLayout');			         
        return mapRecTypeWithLayout  ;     
     }   
   }