force-app/main/default/objects/Account/fields/FNS_CustomerExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_CustomerExtId__c</fullName>
    <description>Customer Id</description>
    <externalId>true</externalId>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Account__c.field-meta.xml
<CustomField>
    <fullName>FNS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Loans</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Loans</relationshipLabel>
    <relationshipName>AccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Loan</relationshipLabel>
    <relationshipName>Financial_Account_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_EffectiveDate__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_ExpiryDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_ProductType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProductType__c</fullName>
    <formula>TEXT(FNS_FinancialAccount__r.FNS_ProductType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_RateType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateType__c</fullName>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
                <default>true</default>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Term__c.field-meta.xml
<CustomField>
    <fullName>FNS_Term__c</fullName>
    <label>Loan Term</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_TermUnit__c.field-meta.xml
<CustomField>
    <fullName>FNS_TermUnit__c</fullName>
    <label>Term Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_ProductType__c/FNS_ProductType__c.object-meta.xml
<CustomObject>
    <label>Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FNS_FinancialAccountDomain.cls
/**************************************************************************
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Domain Class
* @description This class acts as domain class for Financial Account object 
****************************************************************************/
public with sharing class FNS_FinancialAccountDomain {
	/***********************************************************************
	* @description This methods updates FNS_FinancialAccountDomain object records from FFDC 
	* @param Opportunity record's Salesforce Id 
	* @param package namespace value
	* @param financial account object name
	* @param Instance of FNS_FinancialProductPayload class
	* @return instance of financial account object
	************************************************************************/
	public static SObject assignJSONToFinancialAccount(String  applicationID ,String namespace, String finAccountObjName, FNS_FinancialProductPayload financialProduct){
	//For FSC installed package nameSpace is extensionNameSpace for NON FSC installed package baseNameSpace

		Opportunity application;
		if(!String.isEmpty(applicationID)){
			application = FNS_Util.getOpportunityFromAppResp(applicationID);
		}
		Set<ID> accIDSet = new Set<ID>();
		accIDSet.add(application.AccountID);
		List<Account> accList = new FNS_AccountSelector().selectById(accIDSet);
		Account oppBorrower;
		if(accList != null && !accList.isEmpty()){
			oppBorrower = accList[0];
		}
		SObject finAccount   = Schema.getGlobalDescribe().get(finAccountObjName).newSObject();

		finAccount.put(namespace+'FNS_FinancialProductExtId__c',  financialProduct.lineOfCreditId );
		finAccount.put(namespace+'FNS_RateType__c',  financialProduct.rateType );
		finAccount.put(namespace+'FNS_Purpose__c', financialProduct.purposeTypeId );
		if(financialProduct.effectiveDate != null){
			finAccount.put(namespace+'FNS_EffectiveDate__c', FNS_Util.convertStringToDateTime(financialProduct.effectiveDate)); 
		} 
        //API 1.0 changes        
		//finAccount.put(namespace+'FNS_Amount__c', financialProduct.amount);
		//finAccount.put(namespace+'FNS_CurrencyCode__c', financialProduct.currencyCode );
		if(financialProduct.amount!= null)
        {
          finAccount.put(namespace+'FNS_Amount__c', financialProduct.amount.amount);
          finAccount.put(namespace+'FNS_CurrencyCode__c', financialProduct.amount.currencyCode );
        }      
		finAccount.put(namespace+'FNS_ProductType__c',  financialProduct.productType);
		finAccount.put(namespace+'FNS_FinancialAccountTransaction__c',  financialProduct.hostLoanNumber);
		finAccount.put(namespace+'FNS_Term__c', financialProduct.term);
		finAccount.put(namespace+'FNS_TermUnit__c', FNS_Constants.MONTH);
		finAccount.put(namespace+'FNS_OriginationTypeIndicator__c',financialProduct.originationTypeIndicator);
		

		if(financialProduct.expiryDate != null){
			finAccount.put(namespace+'FNS_ExpiryDate__c', FNS_Util.convertStringToDateTime(financialProduct.expiryDate)) ;  
		}

		if(financialProduct.maturityDate != null) {
			finAccount.put(namespace+'FNS_MaturityDate__c', FNS_Util.convertStringToDateTime(financialProduct.maturityDate)) ;  
		}
		//Object relationship management
		if (FNS_Util.isFSCInstalled) {
			if(oppBorrower != null) {
				finAccount.put('FinServ__PrimaryOwner__c', oppBorrower.ID);
				finAccount.put('FinServ__FinancialAccountNumber__c', oppBorrower.FNS_CustomerExtId__c);
			}                         
			finAccount.put(namespace +'FNS_Application__c', application.ID);
		}
		else {
			finAccount.put(namespace +'FNS_Application__c', application.ID);   
			if(oppBorrower !=null){     
				finAccount.put(namespace+'FNS_Account__c', oppBorrower.ID );
			}
		}
		return finAccount;
	} 
}