force-app/main/default/objects/Account/fields/FNS_CustomerDescription__c.field-meta.xml
<CustomField>
    <fullName>FNS_CustomerDescription__c</fullName>
    <description>Customer Description</description>
    <label>Customer Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_CustomerExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_CustomerExtId__c</fullName>
    <description>Customer Id</description>
    <externalId>true</externalId>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_CustomerStruct__c.field-meta.xml
<CustomField>
    <fullName>FNS_CustomerStruct__c</fullName>
    <label>Customer Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Structure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_IdentityNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_IdentityNumber__c</fullName>
    <label>Identity Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_IdentityType__c.field-meta.xml
<CustomField>
    <fullName>FNS_IdentityType__c</fullName>
    <label>Identity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TIN</fullName>
            </value>
            <value>
                <fullName>Organization ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_NAICSCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_NAICSCode__c</fullName>
    <label>NAICS Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_NAICSCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_NaicsDescription__c.field-meta.xml
<CustomField>
    <fullName>FNS_NaicsDescription__c</fullName>
    <label>Naics Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_OfficialType__c.field-meta.xml
<CustomField>
    <fullName>FNS_OfficialType__c</fullName>
    <label>Official Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FNS_SICCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_SICCode__c</fullName>
    <label>SIC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_SICCode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/FNS_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Account__c.field-meta.xml
<CustomField>
    <fullName>FNS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_CustomerProfile__c/FNS_CustomerProfile__c.object-meta.xml
<CustomObject>
    <description>Customer Profile</description>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Customer Profile No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_CustomerProfile__c/fields/FNS_CustomerBusiness__c.field-meta.xml
<CustomField>
    <fullName>FNS_CustomerBusiness__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Profiles</relationshipLabel>
    <relationshipName>CustomerProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_TaxDetails__c/FNS_TaxDetails__c.object-meta.xml
<CustomObject>
    <label>Tax Details</label>
    <nameField>
        <label>Tax Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_TaxDetails__c/fields/FNS_AccountName__c.field-meta.xml
<CustomField>
    <fullName>FNS_AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Name</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TaxDetails</relationshipLabel>
    <relationshipName>TaxDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FNS_NAICSCode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11    Agriculture, Forestry, Fishing and Hunting</fullName>
    </customValue>
    <customValue>
        <fullName>21	Mining, Quarrying, and Oil and Gas Extraction</fullName>
    </customValue>
    <customValue>
        <fullName>22	Utilities</fullName>
    </customValue>
    <customValue>
        <fullName>23	Construction</fullName>
    </customValue>
    <customValue>
        <fullName>31-33	Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>42	Wholesale Trade</fullName>
    </customValue>
    <customValue>
        <fullName>44-45	Retail Trade</fullName>
    </customValue>
    <customValue>
        <fullName>48-49	Transportation and Warehousing</fullName>
    </customValue>
    <customValue>
        <fullName>51	Information</fullName>
    </customValue>
    <customValue>
        <fullName>52	Finance and Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>53	Real Estate and Rental and Leasing</fullName>
    </customValue>
    <customValue>
        <fullName>54	Professional, Scientific, and Technical Services</fullName>
    </customValue>
    <customValue>
        <fullName>55	Management of Companies and Enterprises</fullName>
    </customValue>
    <customValue>
        <fullName>56	Administrative and Support and Waste Management and Remediation Services</fullName>
    </customValue>
    <customValue>
        <fullName>61	Educational Services</fullName>
    </customValue>
    <customValue>
        <fullName>62	Health Care and Social Assistance</fullName>
    </customValue>
    <customValue>
        <fullName>71	Arts, Entertainment, and Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>72	Accommodation and Food Services</fullName>
    </customValue>
    <customValue>
        <fullName>81	Other Services (except Public Administration)</fullName>
    </customValue>
    <customValue>
        <fullName>92	Public Administration</fullName>
    </customValue>
    <masterLabel>NAICSCode</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Structure.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Structure</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_AccountSelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on Account object
****************************************************************************************/
public with sharing class FNS_AccountSelector extends fflib_SObjectSelector{

    String finAccountObjName;

    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/
    public FNS_AccountSelector() {
        super(true, true, true);
    }
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/
    public FNS_AccountSelector(Boolean enforceFLS) {
        super(true, true, false);
    }

    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of Accountobject
        * @param 	   none
        * @return      List of Schema.SObjectField of Accountobject
    **************************************************************************************/ 
    public List<Schema.SObjectField> getSObjectFieldList() {
        
        List<String> fieldList;
    	Map<Schema.SObjectType,List<Schema.SObjectField>> fieldsMap = new Map<Schema.SObjectType,List<Schema.SObjectField>>();    	
    	Map<String, List<String>> objectWithFieldsMap = new Map<String, List<String>>();    	
    	String sobjectName;
    	Schema.SObjectType sObj;
    	string baseNamespace= FNS_Util.getBasePackageNamepace();
        string extNamespace= FNS_Util.getExtensionPackageNamespace();
    	
    	if(FNS_Util.isFSCInstalled){
    		sobjectName = 'Account';
            
    		fieldList = new List<String> {
											baseNamespace+'FNS_CustomerExtId__c', 
										    baseNamespace+'FNS_IdentityNumber__c',
											baseNamespace+'FNS_IdentityType__c',
											baseNamespace+'FNS_OfficialType__c',
											baseNamespace+'FNS_CustomerDescription__c',
                                            baseNamespace+'FNS_NAICSCode__c', 
                                            baseNamespace+'FNS_CustomerStruct__c', 
                                            baseNamespace+'FNS_SICCode__c', 
											 'NaicsDesc'
    									};
			
    	}else {
    		 //For Non FSC 
    		sobjectName = 'Account';
    		fieldList = new List<String> {
    										baseNamespace+'FNS_CustomerExtId__c', 
										    baseNamespace+'FNS_IdentityNumber__c',
											baseNamespace+'FNS_IdentityType__c',
											baseNamespace+'FNS_OfficialType__c',
											baseNamespace+'FNS_CustomerDescription__c',
											baseNamespace+'FNS_NaicsDescription__c',
                                            baseNamespace+'FNS_NAICSCode__c', 
                                            baseNamespace+'FNS_CustomerStruct__c', 
                                            baseNamespace+'FNS_SICCode__c',
                                            baseNamespace+'FNS_NaicsDescription__c'
											
										 };
			
    	}
        fieldList.add('AccountNumber'); 
        fieldList.add('AnnualRevenue'); 
        fieldList.add('SicDesc');
        fieldList.add('Name');
		fieldList.add('Id');
        objectWithFieldsMap.put(sobjectName, fieldList);										  
        fieldsMap = FNS_Util.getSobjectWithFields(objectWithFieldsMap);
        sobj = Schema.getGlobalDescribe().get(sobjectName);
        return  fieldsMap.get(sobj);
    }

    /*************************************************************************************
        * @description Method to return SObject type of Accountobject
        * @param 	   none
        * @return      Returns SObjecttype of Accountobject
    **************************************************************************************/
    public Schema.SObjectType getSObjectType() {
        return Account.sObjectType;
    }

    /*************************************************************************************
        * @description Method to return Accountrecords based on accountIds
        * @param 	   Set of Accountids
        * @return      Returns List of Accountobject
    **************************************************************************************/
    public List<Account> selectById(Set<Id> accountIds) {
        return (List<Account>) selectSObjectsById(accountIds);
    }
    
    /*************************************************************************************
        * @description Method to return Accountrecords based on accountIds
        * @param 	   Set of Account External Ids
        * @return      Returns List of Accountobject
    **************************************************************************************/
    public List<Account> selectByExternalId(Set<String> accountExtIds){
    	fflib_QueryFactory query = newQueryFactory();
		String baseNamespace = FNS_Util.getBasePackageNamepace();
		if(accountExtIds != null && !accountExtIds.isEmpty()){
		    query.setCondition(baseNamespace+'FNS_CustomerExtId__c IN :accountExtIds');
		}
        return (List<Account>) Database.query( query.toSOQL());
	}
	
    /*************************************************************************************
        * @description Method to return Account query along with its child records
        * @param 	   none
        * @return      Returns List of Account object and its associated child records
    **************************************************************************************/
    public fflib_QueryFactory getCustomerSOQL() {
        
        String baseNamespace = FNS_Util.getBasePackageNamepace();
		String addressObjName = baseNamespace+'Addresses__r';
        String custProfileObjName = baseNamespace+'CustomerProfiles__r';
        String taxDetailsObjName = baseNamespace+'TaxDetails__r';
        
        fflib_QueryFactory customerQueryFactory = newQueryFactory(true, true, true);
        customerQueryFactory.assertIsAccessible();
        customerQueryFactory.setEnforceFLS(true);
        if(FNS_Util.checkMCEnabled()){
        	customerQueryFactory.selectField('CurrencyIsoCode');
        }
       
        fflib_QueryFactory addressSubQueryFactory = new FNS_AddressSelector().addQueryFactorySubselect(customerQueryFactory, addressObjName);
		fflib_QueryFactory contactsSubQueryFactory = new FNS_ContactSelector().addQueryFactorySubselect(customerQueryFactory, 'Contacts');
		fflib_QueryFactory customerProfileSubQueryFactory = new FNS_CustomerProfilesSelector().addQueryFactorySubselect(customerQueryFactory, custProfileObjName);
		fflib_QueryFactory taxDetailsSubQueryFactory = new FNS_TaxDetailsSelector().addQueryFactorySubselect(customerQueryFactory, taxDetailsObjName);
        
        return customerQueryFactory;
    }
    
    /*************************************************************************************
        * @description Method to return Account records along with its child records based 
                       on ExternalId
        * @param 	   Set of Account External Ids
        * @return      Returns List of Account object and its associated child records
    **************************************************************************************/
    public List<Account> selectCustomerWithRelatedRecordsByExtId(Set<String> accountExtIds) {
        
        String baseNamespace = FNS_Util.getBasePackageNamepace();
		fflib_QueryFactory accountQueryFactory = getCustomerSOQL();
        
        if(accountExtIds != null && !accountExtIds.isEmpty()){
            accountQueryFactory.setCondition(baseNamespace+'FNS_CustomerExtId__c IN :accountExtIds');
        }
		return (List<Account>) Database.query(accountQueryFactory.toSOQL());
    }
    
    /*************************************************************************************
        * @description Method to return Account records along with its child records based 
                       on Account Id
        * @param 	   Set of Account Ids
        * @return      Returns List of Account object and its associated child records
    **************************************************************************************/
    public List<Account> selectCustomerWithRelatedRecordsById(Set<String> accountIds) {
        
        fflib_QueryFactory accountQueryFactory = getCustomerSOQL();
        if(accountIds != null && !accountIds.isEmpty()){
            accountQueryFactory.setCondition('Id IN :accountIds');
        }
		return (List<Account>) Database.query(accountQueryFactory.toSOQL());
    }

    /*************************************************************************************
        * @description Method to return Account records based on Account record Id
        * @param 	   Account Record Id
        * @return      Returns List of Account object 
    **************************************************************************************/
    public Account getAccountRecord(Id accountRecordId) {
        
        fflib_QueryFactory accountQueryFactory = newQueryFactory(true, true, true);
        //String accountQueryCondition; 
        if(accountRecordId !=  null){
           accountQueryFactory.setCondition('Id =: accountRecordId'); 
        }    
        accountQueryFactory.setLimit(1); 
		return (Account) Database.query(accountQueryFactory.toSOQL());
    }
}