force-app/main/default/objects/Account/fields/FNS_CustomerStruct__c.field-meta.xml
<CustomField>
    <fullName>FNS_CustomerStruct__c</fullName>
    <label>Customer Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Structure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FNS_Customer.recordType-meta.xml
<RecordType>
    <fullName>FNS_Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/FNS_ContactType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ContactType__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_ContactType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/FNS_Contact.recordType-meta.xml
<RecordType>
    <fullName>FNS_Contact</fullName>
    <active>true</active>
    <label>FNS Contact</label>
    
</RecordType>

force-app/main/default/objects/FNS_Address__c/FNS_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Address__c/fields/FNS_CountryCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_CountryCode__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_ProvinceCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProvinceCode__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_State__c.field-meta.xml
<CustomField>
    <fullName>FNS_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/recordTypes/FNS_Address.recordType-meta.xml
<RecordType>
    <fullName>FNS_Address</fullName>
    <active>true</active>
    <label>Address</label>
</RecordType>

force-app/main/default/objects/FNS_Address__c/recordTypes/FNS_AddressReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_AddressReadOnly</fullName>
    <active>true</active>
    <label>Address Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/FNS_ApplicationWithOfficer__c.object-meta.xml
<CustomObject>
    <description>Application with Officer</description>
    <label>Application with Officer</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Application with Officer No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application with Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/fields/FNS_OfficerRole__c.field-meta.xml
<CustomField>
    <fullName>FNS_OfficerRole__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/recordTypes/FNS_ApplicationWithOfficer.recordType-meta.xml
<RecordType>
    <fullName>FNS_ApplicationWithOfficer</fullName>
    <active>true</active>
    <label>Application with Officer</label>
</RecordType>

force-app/main/default/objects/FNS_ApplicationWithOfficer__c/recordTypes/FNS_ApplicationWithOfficerReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_ApplicationWithOfficerReadOnly</fullName>
    <active>true</active>
    <label>Application With Officer Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_Fee__c/FNS_Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FeeType__c.field-meta.xml
<CustomField>
    <fullName>FNS_FeeType__c</fullName>
    <label>Fee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_FeeType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facility</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>FinancialProductFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>LoanFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/recordTypes/FNS_Fee.recordType-meta.xml
<RecordType>
    <fullName>FNS_Fee</fullName>
    <active>true</active>
    <label>Fee</label>
</RecordType>

force-app/main/default/objects/FNS_Fee__c/recordTypes/FNS_FeeReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FeeReadOnly</fullName>
    <active>true</active>
    <label>Fee Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_FeeType__c/FNS_FeeType__c.object-meta.xml
<CustomObject>
    <label>Fee Type</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Fee Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_ProductType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProductType__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Purpose__c.field-meta.xml
<CustomField>
    <fullName>FNS_Purpose__c</fullName>
    <label>Purpose</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Purpose</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Status__c.field-meta.xml
<CustomField>
    <fullName>FNS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Paid out</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_SuppCurrencies__c.field-meta.xml
<CustomField>
    <fullName>FNS_SuppCurrencies__c</fullName>
    <label>Supported Currencies</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_ConfigCurrency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/recordTypes/FNS_FinancialAccount.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccount</fullName>
    <active>true</active>
    <label>Financial Product</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccount__c/recordTypes/FNS_FinancialAccountReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountReadOnly</fullName>
    <active>true</active>
    <description>This record type will have only read only fields</description>
    <label>Financial Product Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountRole__c/FNS_FinancialAccountRole__c.object-meta.xml
<CustomObject>
    <label>Product Role (NonFSC)</label>
    <nameField>
        <label>Product Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Roles (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountRole__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Product Roles (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountRoles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountRole__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>Financial_Account_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountRole__c/fields/FNS_ProductRelRole__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProductRelRole__c</fullName>
    <label>Product Relationship Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountRole__c/fields/FNS_TypeofProdRole__c.field-meta.xml
<CustomField>
    <fullName>FNS_TypeofProdRole__c</fullName>
    <label>Type of Product Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountRole__c/recordTypes/FNS_FinancialAccountRole.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountRole</fullName>
    <active>true</active>
    <label>Financial Product Role</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountRole__c/recordTypes/FNS_FinancialAccountRoleReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountRoleReadOnly</fullName>
    <active>true</active>
    <label>Financial Product Role Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Loans (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_LoanProductType__c.field-meta.xml
<CustomField>
    <fullName>FNS_LoanProductType__c</fullName>
    <label>Loan Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_ProductType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_LoanPurpose__c.field-meta.xml
<CustomField>
   <fullName>FNS_LoanPurpose__c</fullName>
    <label>Loan Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Purpose</valueSetName>
    </valueSet>

</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_PricingFrequency__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingFrequency__c</fullName>
    <label>Pricing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_PricingType__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingType__c</fullName>
    <label>Pricing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_PricingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_ProductType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProductType__c</fullName>
    <formula>TEXT(FNS_FinancialAccount__r.FNS_ProductType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/recordTypes/FNS_FinancialAccountTransaction.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountTransaction</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/recordTypes/FNS_FinancialAccountTransactionReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_FinancialAccountTransactionReadOnly</fullName>
    <active>true</active>
    <label>Loan Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_Pricing__c/FNS_Pricing__c.object-meta.xml
<CustomObject>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
 	<displayFormat>PN -{0000}</displayFormat>     
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Product</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Pricings</relationshipLabel>
    <relationshipName>FinancialProductPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Pricings</relationshipLabel>
    <relationshipName>LoanPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>FNS_Frequencies__c</fullName>
    <label>Frequencies</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_PricingType__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingType__c</fullName>
    <label>Pricing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_PricingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/recordTypes/FNS_Pricing.recordType-meta.xml
<RecordType>
    <fullName>FNS_Pricing</fullName>
    <active>true</active>
    <label>Pricing</label>
</RecordType>

force-app/main/default/objects/FNS_Pricing__c/recordTypes/FNS_PricingReadOnly.recordType-meta.xml
<RecordType>
    <fullName>FNS_PricingReadOnly</fullName>
    <active>true</active>
    <label>Pricing Read Only</label>
</RecordType>

force-app/main/default/objects/FNS_ProductType__c/FNS_ProductType__c.object-meta.xml
<CustomObject>
    <label>Product Type</label>
    <nameField>
        <label>Product Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/FNS_Task.recordType-meta.xml
<RecordType>
    <fullName>FNS_Task</fullName>
    <active>true</active>
    <label>Task</label>
    
</RecordType>

force-app/main/default/globalValueSets/FNS_ConfigCurrency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>ConfigCurrency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_ContactType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>ContactType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_FeeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>FeeType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_PricingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>PricingType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>ProductType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Province.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Province</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Purpose.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Purpose</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Structure.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Structure</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_RecordTypeUpdate.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Configuration API
  * @description This class is used to update the picklist value in the Record Types.
****************************************************************************************/
public class FNS_RecordTypeUpdate{
    @future(callout=true)
    public static void UpdateRecordType(List<String> configList) {
        //FNS_ConfigurationDomain configDomain =new FNS_ConfigurationDomain();
          Map<String,List<RecordTypeWrapper>> globalValRecordTypeMap =getMapOfObjAndRecordType();
       // List<String> configList = New List<String>{'Structure','ConfigCurrency','TrackingItemStatus','State','Disposition','Role','FeeType','ProductType','DocumentPriority','PricingType','Frequency','Purpose','PaymentType','ContactType','Province','Country'};
          for(String configType : configList){
                if(globalValRecordTypeMap !=null && globalValRecordTypeMap.containsKey(configType)){
                    List<RecordTypeWrapper> recordTypeWrapList= globalValRecordTypeMap.get(configType);
                    system.debug('recordTypeWrapList>>'+recordTypeWrapList);
                    for(RecordTypeWrapper recordType : recordTypeWrapList){
                        for(String recordTypeDevName : recordType.recordTypeDeveloperName){
                        FNS_UpdateMetadata.UpdateRecordType(recordType.objectName, recordType.fieldName, recordTypeDevName);
                        }
                    }
        		}
          }
    }
    public class RecordTypeWrapper{
        String objectName;
        String fieldName;
		List<String> recordTypeDeveloperName;
    }
    /*************************************************************************************
    * @description  Method to get List of Object and Record Type map 
    * @Params       none
    * @Returns      List of Object and Record Type map 
    * @author       Brillio
    **************************************************************************************/ 
    public static Map<String,List<RecordTypeWrapper>> getMapOfObjAndRecordType(){
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        String extNamespace= FNS_Util.getExtensionPackageNamespace();
        String namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        String finAccountObjName;
        String finFinancialAccountTransactionObjName;
        string finFinancialAccountRoleObjName;
        if(FNS_Util.isFSCInstalled){
            finAccountObjName = 'FinServ__FinancialAccount__c' ;
            finFinancialAccountTransactionObjName ='FinServ__FinancialAccountTransaction__c' ;
            finFinancialAccountRoleObjName = 'FinServ__FinancialAccountRole__c'; 
        }
        else{
            finAccountObjName = baseNamespace+'FNS_FinancialAccount__c' ;
            finFinancialAccountTransactionObjName = baseNamespace+'FNS_FinancialAccountTransaction__c' ;
            finFinancialAccountRoleObjName = baseNamespace+'FNS_FinancialAccountRole__c'; 
        }
        Map<String,List<RecordTypeWrapper>> constructGlobalValRecordTypeMap = new Map<String,List<RecordTypeWrapper>>();
        
        //Fee Type
        RecordTypeWrapper feeRecordType= new RecordTypeWrapper();
        feeRecordType.objectName =baseNamespace+'FNS_Fee__c';
        feeRecordType.fieldName=baseNamespace+'FNS_FeeType__c';
        feeRecordType.recordTypeDeveloperName=new List<String>{baseNamespace+'FNS_Fee',baseNamespace+'FNS_FeeReadOnly'};
        constructGlobalValRecordTypeMap.put('FeeType',new List<RecordTypeWrapper>{feeRecordType});
       
        //Contact Type
        RecordTypeWrapper contactRecordType= new RecordTypeWrapper();
        contactRecordType.objectName ='Contact';
        contactRecordType.fieldName='FNS_ContactType__c';
        contactRecordType.recordTypeDeveloperName=new List<String>{'FNS_Contact'};
        constructGlobalValRecordTypeMap.put('ContactType',new List<RecordTypeWrapper>{contactRecordType});
        
        //Pricing Type
        RecordTypeWrapper pricingTypRecordType= new RecordTypeWrapper();
        pricingTypRecordType.objectName ='FNS_Pricing__c';
        pricingTypRecordType.fieldName='FNS_PricingType__c';
        pricingTypRecordType.recordTypeDeveloperName=new List<String>{'FNS_Pricing','FNS_PricingReadOnly'};
            
        RecordTypeWrapper finAccpricingTypRecordType= new RecordTypeWrapper();
        finAccpricingTypRecordType.objectName =finFinancialAccountTransactionObjName;
        finAccpricingTypRecordType.fieldName='FNS_PricingType__c';
        finAccpricingTypRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccountTransaction','FNS_FinancialAccountTransactionReadOnly'};
        constructGlobalValRecordTypeMap.put('PricingType',new List<RecordTypeWrapper>{pricingTypRecordType,finAccpricingTypRecordType});
        
        //Pricing Feequency
        RecordTypeWrapper pricingFreRecordType= new RecordTypeWrapper();
        pricingFreRecordType.objectName ='FNS_Pricing__c';
        pricingFreRecordType.fieldName='FNS_Frequencies__c';
        pricingFreRecordType.recordTypeDeveloperName=new List<String>{'FNS_Pricing','FNS_PricingReadOnly'};
            
        RecordTypeWrapper finAccpricingFreRecordType= new RecordTypeWrapper();
        finAccpricingFreRecordType.objectName =finFinancialAccountTransactionObjName;
        finAccpricingFreRecordType.fieldName='FNS_PricingFrequency__c';
        finAccpricingFreRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccountTransaction','FNS_FinancialAccountTransactionReadOnly'};
        constructGlobalValRecordTypeMap.put('Frequency',new List<RecordTypeWrapper>{pricingFreRecordType,finAccpricingFreRecordType});
        
        
        
        //Product Type Fin Account
        RecordTypeWrapper productTypeRecordType= new RecordTypeWrapper();
        productTypeRecordType.objectName = finAccountObjName;
        productTypeRecordType.fieldName='FNS_ProductType__c';
        productTypeRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccount','FNS_FinancialAccountReadOnly'};
        
        //Product Type Fin Account Transaction
        RecordTypeWrapper finAccTranProductTypeRecordType= new RecordTypeWrapper();
        finAccTranProductTypeRecordType.objectName = finFinancialAccountTransactionObjName;
        finAccTranProductTypeRecordType.fieldName='FNS_LoanProductType__c';
        finAccTranProductTypeRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccountTransaction','FNS_FinancialAccountTransactionReadOnly'};
        constructGlobalValRecordTypeMap.put('ProductType',new List<RecordTypeWrapper>{productTypeRecordType,finAccTranProductTypeRecordType});
       
        //Purpose Fin Account
        RecordTypeWrapper PurposeRecordType= new RecordTypeWrapper();
        PurposeRecordType.objectName = finAccountObjName;
        PurposeRecordType.fieldName='FNS_Purpose__c';
        PurposeRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccount','FNS_FinancialAccountReadOnly'};
        
        //Purpose Fin Account Transaction
        RecordTypeWrapper finAccTranPurposeRecordType= new RecordTypeWrapper();
        finAccTranPurposeRecordType.objectName = finFinancialAccountTransactionObjName;
        finAccTranPurposeRecordType.fieldName='FNS_LoanPurpose__c';
        finAccTranPurposeRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccountTransaction','FNS_FinancialAccountTransactionReadOnly'};
        constructGlobalValRecordTypeMap.put('Purpose',new List<RecordTypeWrapper>{PurposeRecordType,finAccTranPurposeRecordType});
        
        //Purpose Fin Account Transaction
        RecordTypeWrapper productRelationshipRoleRecordType= new RecordTypeWrapper();
        productRelationshipRoleRecordType.objectName = finFinancialAccountRoleObjName;
        productRelationshipRoleRecordType.fieldName='FNS_ProductRelRole__c';
        productRelationshipRoleRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccountRole','FNS_FinancialAccountRoleReadOnly'};
            
        RecordTypeWrapper typeofProductRoleRecordType= new RecordTypeWrapper();
        typeofProductRoleRecordType.objectName = finFinancialAccountRoleObjName;
        typeofProductRoleRecordType.fieldName='FNS_TypeofProdRole__c';
        typeofProductRoleRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccountRole','FNS_FinancialAccountRoleReadOnly'};
            
        RecordTypeWrapper applicationwithOfficerRecordType= new RecordTypeWrapper();
        applicationwithOfficerRecordType.objectName = 'FNS_ApplicationWithOfficer__c';
        applicationwithOfficerRecordType.fieldName='FNS_OfficerRole__c';
        applicationwithOfficerRecordType.recordTypeDeveloperName=new List<String>{'FNS_ApplicationWithOfficer','FNS_ApplicationWithOfficerReadOnly'};
        constructGlobalValRecordTypeMap.put('Role',new List<RecordTypeWrapper>{productRelationshipRoleRecordType,typeofProductRoleRecordType,applicationwithOfficerRecordType});
        
        RecordTypeWrapper finAccSupporCurrencyRecordType= new RecordTypeWrapper();
        finAccSupporCurrencyRecordType.objectName = finAccountObjName;
        finAccSupporCurrencyRecordType.fieldName='FNS_SuppCurrencies__c';
        finAccSupporCurrencyRecordType.recordTypeDeveloperName=new List<String>{'FNS_FinancialAccount','FNS_FinancialAccountReadOnly'};
        constructGlobalValRecordTypeMap.put('ConfigCurrency',new List<RecordTypeWrapper>{finAccSupporCurrencyRecordType});
        
        RecordTypeWrapper addressStateRecordType= new RecordTypeWrapper();
        addressStateRecordType.objectName = 'FNS_Address__c';
        addressStateRecordType.fieldName='FNS_State__c';
        addressStateRecordType.recordTypeDeveloperName=new List<String>{'FNS_Address','FNS_AddressReadOnly'};
        constructGlobalValRecordTypeMap.put('State',new List<RecordTypeWrapper>{addressStateRecordType});
        
        RecordTypeWrapper taskStatusRecordType= new RecordTypeWrapper();
        taskStatusRecordType.objectName = 'Task';
        taskStatusRecordType.fieldName='FNS_Status__c';
        taskStatusRecordType.recordTypeDeveloperName=new List<String>{'FNS_Task'};
		
        constructGlobalValRecordTypeMap.put('TrackingItemStatus',new List<RecordTypeWrapper>{taskStatusRecordType});
        
        RecordTypeWrapper accStructureRecordType= new RecordTypeWrapper();
        accStructureRecordType.objectName = 'Account';
        accStructureRecordType.fieldName='FNS_CustomerStruct__c';
        accStructureRecordType.recordTypeDeveloperName=new List<String>{'FNS_Customer'};
        constructGlobalValRecordTypeMap.put('Structure',new List<RecordTypeWrapper>{accStructureRecordType});
        
        RecordTypeWrapper taskPriorityRecordType= new RecordTypeWrapper();
        taskPriorityRecordType.objectName = 'Task';
        taskPriorityRecordType.fieldName='FNS_Priority__c';
        taskPriorityRecordType.recordTypeDeveloperName=new List<String>{'FNS_Task'};
        constructGlobalValRecordTypeMap.put('DocumentPriority',new List<RecordTypeWrapper>{taskPriorityRecordType});
		
        RecordTypeWrapper addressProvinceRecordType= new RecordTypeWrapper();
        addressProvinceRecordType.objectName = 'FNS_Address__c';
        addressProvinceRecordType.fieldName='FNS_ProvinceCode__c';
        addressProvinceRecordType.recordTypeDeveloperName=new List<String>{'FNS_Address','FNS_AddressReadOnly'};
        constructGlobalValRecordTypeMap.put('Province',new List<RecordTypeWrapper>{addressProvinceRecordType});
		
        RecordTypeWrapper addressCountryRecordType= new RecordTypeWrapper();
        addressCountryRecordType.objectName = 'FNS_Address__c';
        addressCountryRecordType.fieldName='FNS_CountryCode__c';
        addressCountryRecordType.recordTypeDeveloperName=new List<String>{'FNS_Address','FNS_AddressReadOnly'};
        constructGlobalValRecordTypeMap.put('Country',new List<RecordTypeWrapper>{addressCountryRecordType});		
		
        return constructGlobalValRecordTypeMap;
    }
}