force-app/main/default/objects/FNS_ProcessGroup__c/FNS_ProcessGroup__c.object-meta.xml
<CustomObject>
    <label>Process Group</label>
    <nameField>
        <label>Process Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProcessGroup__c/fields/FNS_Description__c.field-meta.xml
<CustomField>
    <fullName>FNS_Description__c</fullName>
    <label>Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessGroup__c/fields/FNS_InactiveIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_InactiveIndicator__c</fullName>
    <label>Inactive Indicator</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessGroup__c/fields/FNS_NextDefaultProcessGroupId__c.field-meta.xml
<CustomField>
    <fullName>FNS_NextDefaultProcessGroupId__c</fullName>
    <label>Next Default Process Group Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessGroup__c/fields/FNS_ProcessGroupExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessGroupExtId__c</fullName>
    <externalId>true</externalId>
    <label>Process Group Ext Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessGroup__c/recordTypes/FNS_ProcessGroup.recordType-meta.xml
<RecordType>
    <fullName>FNS_ProcessGroup</fullName>
    <active>true</active>
    <label>Process Group</label>
</RecordType>

force-app/main/default/classes/FNS_ProcessGroupDomain.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Configuration API
  * @description This class is used to perform DML using json for an Application.
****************************************************************************************/
public with sharing class FNS_ProcessGroupDomain {

    static FNS_ErrorLog logger = new FNS_ErrorLog();
    
    public static Object getConfigurations(){

        Map<String, Object> objValue = new Map<String, Object> {
            FNS_Constants.API_RESPONSE => FNS_Constants.API_EMPTY,
            FNS_Constants.API_ERROR => FNS_Constants.API_EMPTY
            };

        try {

            fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] { FNS_ProcessGroup__c.SObjectType });
            FNS_UpsertUnitOfWorkHelper upsertProcessGroups = new FNS_UpsertUnitOfWorkHelper();
            uow.registerWork(upsertProcessGroups);
            
            FNS_IntegrationUtil.FNS_RequestParam param = new FNS_IntegrationUtil.FNS_RequestParam();
            param.objectName = FNS_Constants.CLASS_PROCESS_GROUPS;
            param.endPoint = FNS_Constants.URL_PROCESS_GROUPS;
            param.methodName = FNS_Constants.METHOD_GET;
            FNS_JSONAPIRouter router = new FNS_JSONAPIRouter();
            HttpResponse jsonResponse = router.getPostRequest(param);
            if(jsonResponse.getStatusCode() == 200){
                if (!String.isEmpty(jsonResponse.getBody())){
                    List<FNS_ProcessGroup__c> processGroupList = new List<FNS_ProcessGroup__c>();            
                    ///List<FNS_ObjectContainer.FNS_ProcessGroup> processGroupConfigList = (List<FNS_ObjectContainer.FNS_ProcessGroup>)JSON.deserialize(jsonResponse.getBody(), List<FNS_ObjectContainer.FNS_ProcessGroup>.class);            
                    //for(FNS_ObjectContainer.FNS_ProcessGroup pcpayload : processGroupConfigList){
                    FNS_ObjectContainer processGroupConfigList = (FNS_ObjectContainer)JSON.deserialize(jsonResponse.getBody(), FNS_ObjectContainer.class);            
                    for(FNS_ObjectContainer.FNS_ProcessGroup pcpayload : processGroupConfigList.processGroupsList){
                    
                        FNS_ProcessGroup__c processGroup = new FNS_ProcessGroup__c();
                        processGroup = FNS_ProcessGroupDomain.assignJSONToActivities(pcpayload);
                        upsertProcessGroups.registerProcessGroupUpsert(processGroup);
                    }
                    
                    FNS_ObjectAccessContainer.checkProcessGroupAccess(FNS_AccessController.DML_OPERATION_UPSERT);
                    uow.commitWork();                    
                    
                    objValue.put(FNS_Constants.API_RESPONSE,jsonResponse.getBody());		
                }   
            }
        } catch (DMLException ex){
            logger.addLogRecord('FNS_ProcessGroupDomain', 'getConfigurations', ex.getMessage() + ex.getStackTraceString());
            objValue.put(FNS_Constants.API_ERROR,ex.getMessage());
        } catch (Exception ex){
            logger.addLogRecord('FNS_ProcessGroupDomain', 'getConfigurations', ex.getMessage() + ex.getStackTraceString());
            objValue.put(FNS_Constants.API_ERROR,ex.getMessage());
        }
        return objValue; 
    }
    //Keerthi - Mapping the fields
    public static FNS_ProcessGroup__c assignJSONToActivities(FNS_ObjectContainer.FNS_ProcessGroup processGroup){
        FNS_ProcessGroup__c processGroupObj = new FNS_ProcessGroup__c();

        try {
            processGroupObj.FNS_Description__c = processGroup.description;
            processGroupObj.FNS_NextDefaultProcessGroupId__c = processGroup.nextDefaultProcessGroupId;
            processGroupObj.FNS_InactiveIndicator__c = processGroup.inactiveIndicator;        
            processGroupObj.FNS_ProcessGroupExtId__c = processGroup.processGroupId;
        } catch (Exception ex){
            logger.addLogRecord('FNS_ProcessGroupDomain', 'assignJSONToActivities', ex.getMessage() + ex.getStackTraceString()); 
        }
        return processGroupObj;
    }
    
}