force-app/main/default/objects/FNS_ProcessCenter__c/FNS_ProcessCenter__c.object-meta.xml
<CustomObject>
    <label>Process Center</label>
    <nameField>
        <label>Process Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_AddressLine__c.field-meta.xml
<CustomField>
    <fullName>FNS_AddressLine__c</fullName>
    <description>Address Line 2</description>
    <label>Address Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_City__c.field-meta.xml
<CustomField>
    <fullName>FNS_City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_County__c.field-meta.xml
<CustomField>
    <fullName>FNS_County__c</fullName>
    <description>County</description>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_ProcessCenterExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessCenterExtId__c</fullName>
    <description>processCenterId</description>
    <externalId>true</externalId>
    <label>Process Center Ext Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_ProcessCenterNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessCenterNumber__c</fullName>
    <description>Number</description>
    <label>Process Center Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_State__c.field-meta.xml
<CustomField>
    <fullName>FNS_State__c</fullName>
    <label>State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_StreetName__c.field-meta.xml
<CustomField>
    <fullName>FNS_StreetName__c</fullName>
    <description>Street Name</description>
    <label>Street Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_StreetNumber__c</fullName>
    <description>Street Number</description>
    <label>Street Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/fields/FNS_Zip__c.field-meta.xml
<CustomField>
    <fullName>FNS_Zip__c</fullName>
    <description>Zip Code</description>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ProcessCenter__c/recordTypes/FNS_ProcessCenter.recordType-meta.xml
<RecordType>
    <fullName>FNS_ProcessCenter</fullName>
    <active>true</active>
    <label>Process Center</label>
</RecordType>

force-app/main/default/classes/FNS_ProcessCenterDomain.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Configuration API
  * @description This class is used to perform DML using json for an ProcessCenter.
****************************************************************************************/
public with sharing class FNS_ProcessCenterDomain {

    static FNS_ErrorLog logger = new FNS_ErrorLog();
    
    public static Object getConfigurations(){     

        Map<String, Object> objValue = new Map<String, Object> {
            FNS_Constants.API_RESPONSE => FNS_Constants.API_EMPTY,
            FNS_Constants.API_ERROR => FNS_Constants.API_EMPTY
            };

        try {

            fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] { FNS_ProcessCenter__c.SObjectType });
            FNS_UpsertUnitOfWorkHelper upsertProcessCenters = new FNS_UpsertUnitOfWorkHelper();
            uow.registerWork(upsertProcessCenters);

            FNS_IntegrationUtil.FNS_RequestParam param = new FNS_IntegrationUtil.FNS_RequestParam();
            param.objectName = FNS_Constants.CLASS_PROCESS_CENTERS;
            param.endPoint = FNS_Constants.URL_PROCESS_CENTERS;
            param.methodName = FNS_Constants.METHOD_GET;
            FNS_JSONAPIRouter router = new FNS_JSONAPIRouter();
            HttpResponse jsonResponse = router.getPostRequest(param);
            if(jsonResponse.getStatusCode() == 200){
                if (!String.isEmpty(jsonResponse.getBody())){
                    List<FNS_ProcessCenter__c> processCenterList = new List<FNS_ProcessCenter__c>(); 
                    //List<FNS_ObjectContainer.FNS_ProcessCenter> processCenterConfigList = (List<FNS_ObjectContainer.FNS_ProcessCenter>)JSON.deserialize(jsonResponse.getBody(), List<FNS_ObjectContainer.FNS_ProcessCenter>.class);
                    //for(FNS_ObjectContainer.FNS_ProcessCenter pcpayload : processCenterConfigList){
                    FNS_ObjectContainer processCenterConfigList = (FNS_ObjectContainer)JSON.deserialize(jsonResponse.getBody(), FNS_ObjectContainer.class);
                    for(FNS_ObjectContainer.FNS_ProcessCenter pcpayload : processCenterConfigList.processCentersList){
                    	FNS_ProcessCenter__c processCenter = new FNS_ProcessCenter__c();
                        processCenter = FNS_ProcessCenterDomain.assignJSONToActivities(pcpayload);
                        upsertProcessCenters.registerProcessCenterUpsert(processCenter);
                    }
                    
                    FNS_ObjectAccessContainer.checkProcessCenterAccess(FNS_AccessController.DML_OPERATION_UPSERT);
                    uow.commitWork();                   
                
                    objValue.put(FNS_Constants.API_RESPONSE,jsonResponse.getBody());		
                }   
            }
        } catch (DMLException ex){
            logger.addLogRecord('FNS_ProcessCenterDomain', 'getConfigurations', ex.getMessage() + ex.getStackTraceString());
            objValue.put(FNS_Constants.API_ERROR,ex.getMessage());
        } catch (Exception ex){
            logger.addLogRecord('FNS_ProcessCenterDomain', 'getConfigurations', ex.getMessage() + ex.getStackTraceString());
            objValue.put(FNS_Constants.API_ERROR,ex.getMessage());
        }
        return objValue;
    }
    //Keerthi - Mapping the fields
    public static FNS_ProcessCenter__c assignJSONToActivities(FNS_ObjectContainer.FNS_ProcessCenter processCenter){
        FNS_ProcessCenter__c processCenterObj = new FNS_ProcessCenter__c();
        try {
            processCenterObj.FNS_State__c = processCenter.state;
            processCenterObj.Name = processCenter.processCenterName;
            processCenterobj.FNS_ProcessCenterNumber__c = processCenter.processCenterNumber;
            processCenterObj.FNS_StreetNumber__c = processCenter.streetNumber;
            processCenterObj.FNS_StreetName__c = processCenter.streetName;
            processCenterObj.FNS_AddressLine__c = processCenter.addressLine1;
            processCenterObj.FNS_City__c = processCenter.city;
            processCenterObj.FNS_County__c = processCenter.county;
            processCenterObj.FNS_Zip__c = processCenter.zip;
            processCenterobj.FNS_ProcessCenterExtId__c = processCenter.processCenterId;
        } catch (Exception ex){
            logger.addLogRecord('FNS_ProcessCenterDomain', 'assignJSONToActivities', ex.getMessage() + ex.getStackTraceString()); 
        }
        return processCenterObj;
    }
    
}