force-app/main/default/objects/FNS_Fee__c/FNS_Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <description>Fee Amount</description>
    <label>Fee Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_CurrencyCode__c</fullName>
    <description>Currency Code</description>
    <label>Currency Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FeeRate__c.field-meta.xml
<CustomField>
    <fullName>FNS_FeeRate__c</fullName>
    <description>Accrual Rate</description>
    <label>Fee Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FeeType__c.field-meta.xml
<CustomField>
    <fullName>FNS_FeeType__c</fullName>
    <label>Fee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_FeeType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facility</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>FinancialProductFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>LoanFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FeeType__c/FNS_FeeType__c.object-meta.xml
<CustomObject>
    <label>Fee Type</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Fee Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_CurrencyCode__c</fullName>
    <label>Currency</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Loans (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FNS_FeeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>FeeType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_FeeSelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on Custom object Fee
****************************************************************************************/
public with sharing class FNS_FeeSelector extends fflib_SObjectSelector{
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/
    public FNS_FeeSelector(){
        super(true, true, true);
    }
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/
    public FNS_FeeSelector(Boolean enforceFLS){
        super(true, true, false);
    }
    
    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of Custom object Fee
        * @param 	   none
        * @return      List of Schema.SObjectField of Custom object Fee
    **************************************************************************************/ 
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            FNS_Fee__c.Id,
            FNS_Fee__c.FNS_Amount__c,
            FNS_Fee__c.FNS_CurrencyCode__c,
            FNS_Fee__c.FNS_FeeRate__c,
            FNS_Fee__c.FNS_FeeType__c,
            FNS_Fee__c.FNS_FinancialAccount__c,
            FNS_Fee__c.FNS_BypassValidation__c,
            FNS_Fee__c.FNS_FinancialAccountTransaction__c
        };
    }
    
    /*************************************************************************************
        * @description Method to return SObject type of Custom object Fee
        * @param 	   none
        * @return      Returns SObjecttype of Custom object Fee
    **************************************************************************************/ 
    public Schema.SObjectType getSObjectType(){
        return FNS_Fee__c.sObjectType;
    }
    
    /*************************************************************************************
        * @description Method to return Custom Fee records based on feeIds
        * @param 	   Set of Fee Ids
        * @return      Returns List of Custom object Fee
    **************************************************************************************/
    public List<FNS_Fee__c> selectById(Set<Id> feeIds){
        return (List<FNS_Fee__c>) selectSObjectsById(feeIds);
    }
    
    /*************************************************************************************
        * @description Method to return Custom Fee records based on productIds
        * @param 	   Set of Product Ids
        * @return      Returns List of Custom object Fee
    **************************************************************************************/
    public List<FNS_Fee__c> getFees(Set<Id> productIds){
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        String extNamespace= FNS_Util.getExtensionPackageNamespace();
        String namespace= FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
        
        fflib_QueryFactory feeQueryFactory = newQueryFactory(true, true, true);
        feeQueryFactory.assertIsAccessible();
        feeQueryFactory.setEnforceFLS(true);
        String feeQueryCondition = '';
        List<String> feeQueryConditions = new List<String>();
        
        if(productIds != null && !productIds.isEmpty()){
            if(FNS_Util.isFSCInstalled){
            	feeQueryCondition = extNamespace + 'FNS_FinancialAccountFSC__c IN : productIds';
            }else {
            	feeQueryCondition = baseNamespace + 'FNS_FinancialAccount__c IN : productIds';
            }
        }
        feeQueryConditions.add(feeQueryCondition);
        if(! feeQueryConditions.isEmpty()){
            feeQueryFactory.setCondition(String.join(feeQueryConditions, ' AND '));
        }
		
        return (List<FNS_Fee__c>) Database.query(feeQueryFactory.toSOQL());
    }   
}