force-app/main/default/objects/FNS_Fee__c/FNS_Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <description>Fee Amount</description>
    <label>Fee Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_CurrencyCode__c</fullName>
    <description>Currency Code</description>
    <label>Currency Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FeeRate__c.field-meta.xml
<CustomField>
    <fullName>FNS_FeeRate__c</fullName>
    <description>Accrual Rate</description>
    <label>Fee Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FeeType__c.field-meta.xml
<CustomField>
    <fullName>FNS_FeeType__c</fullName>
    <label>Fee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_FeeType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/recordTypes/FNS_Fee.recordType-meta.xml
<RecordType>
    <fullName>FNS_Fee</fullName>
    <active>true</active>
    <label>Fee</label>
</RecordType>

force-app/main/default/objects/FNS_FeeType__c/FNS_FeeType__c.object-meta.xml
<CustomObject>
    <label>Fee Type</label>
    <nameField>
        <displayFormat>FT-{00000}</displayFormat>
        <label>Fee Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/FNS_FeeType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>FeeType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_FeeDomain.cls
/**************************************************************************
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Domain Class
* @description This class acts as domain class for Fee object 
****************************************************************************/
public with sharing class FNS_FeeDomain {
    /***********************************************************************
    * @description This methods converts json response to Fee object
    * @param Instance of FNS_ObjectContainer.FNS_Fee class
    * @return instance of Fee object
    ************************************************************************/
    
    public static FNS_Fee__c assignJSONToFee(FNS_ObjectContainer.FNS_Fee feeRec){
        FNS_Fee__c fee = new FNS_Fee__c();
        if(feeRec.accrualRate != null){
        	fee.FNS_FeeRate__c = feeRec.accrualRate;
        }
        //  API 1.0 changes 
        //fee.FNS_Amount__c =  feeRec.amount;
         if( feeRec.feeAmount != null)
        {
            fee.FNS_Amount__c =  feeRec.feeAmount.amount;
            //fee.FNS_CurrencyCode__c = feeRec.feeAmount.currencyCode;
        } 
        else
        {
           fee.FNS_Amount__c  = 0.0 ;
        } 
        fee.FNS_CurrencyCode__c = FNS_Constants.DEFAULT_CURRENCY; // Temp Hard coding
        fee.FNS_FeeType__c = feeRec.feeTypeId;
        
        return fee;
    } 
}