force-app/main/default/objects/FNS_Fee__c/FNS_Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <description>Fee Amount</description>
    <label>Fee Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Facility</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>FinancialProductFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Fee__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Fees</relationshipLabel>
    <relationshipName>LoanFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/FNS_FinancialAccount__c.object-meta.xml
<CustomObject>
    <label>Financial Product (NonFSC)</label>
    <nameField>
        <label>Financial Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application</relationshipLabel>
    <relationshipName>FinancialAccountApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccount__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <externalId>true</externalId>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/FNS_FinancialAccountTransaction__c.object-meta.xml
<CustomObject>
    <label>Loan (NonFSC)</label>
    <nameField>
        <label>Loan Name</label>
        <type>AutoNumber</type>
	<displayFormat>FAT -{0000}</displayFormat>
    </nameField>
    <pluralLabel>Loans (NonFSC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FNS_FinancialAccountTransaction__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Loans (NonFSC)</relationshipLabel>
    <relationshipName>FinancialAccountLoans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/FNS_Pricing__c.object-meta.xml
<CustomObject>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
 	<displayFormat>PN -{0000}</displayFormat>     
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>FNS_BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccount__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Product</description>
    <label>Financial Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Pricings</relationshipLabel>
    <relationshipName>FinancialProductPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_FinancialAccountTransaction__c.field-meta.xml
<CustomField>
    <fullName>FNS_FinancialAccountTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan</description>
    <label>Loan</label>
    <referenceTo>FNS_FinancialAccountTransaction__c</referenceTo>
    <relationshipLabel>Loan Pricings</relationshipLabel>
    <relationshipName>LoanPricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_BypassValidation__c.field-meta.xml
<CustomField>
    <fullName>FNS_BypassValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
    
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_Fees__c.field-meta.xml
<CustomField>
    <fullName>FNS_Fees__c</fullName>
    <label>Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_LoanAmount__c.field-meta.xml
<CustomField>
    <fullName>FNS_LoanAmount__c</fullName>
    <description>Loan Amount</description>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_TotalRequestedAmount__c.field-meta.xml
<CustomField>
    <fullName>FNS_TotalRequestedAmount__c</fullName>
    <label>Total Requested Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FNS_ApplicationRollup.cls
/*****************************************************************************************
 * Copyright (c) 2019, Brillio
 * All rights reserved.
 * @author Brillio
 * @date 2019
 * @group Access Handler
 * @description This class is used to pull summary data for Application.

 ******************************************************************************************/
public with sharing class FNS_ApplicationRollup {
    static string baseNamespace  = FNS_Util.getBasePackageNamepace(); 
    static string extNamespace  = FNS_Util.getExtensionPackageNamespace() ;
    static string namespace = FNS_Util.isFSCInstalled?extNamespace:baseNamespace;
    static String finAccountObjName ;
    static String finFinancialAccountTransactionObjName ;
    static String finFinancialAccountRoleObjName ;
    static Schema.SObjectType finAccountObject;
    static Schema.SObjectType finFinancialAccountTransactionObject;
    static Schema.SObjectType finFinancialAccountRoleObject ;
    static fflib_SObjectUnitOfWork uow ;  // SObjects (in order of dependency)
    static string productLoanRelationShipName ;
    static string productPricngRelationShipName ;
    static string productFeeRelationShipName ;
    static FNS_ErrorLog logger = new FNS_ErrorLog();
    static {
        initCode();
    }
    
  /***********************************************************************
  * @description This method initializes all the static variables when class is initialized
  * @param none
  * @return none
  ************************************************************************/
  private static void initCode() {
    /*if(FNS_Util.isFSCInstalled){
      finAccountObjName = 'FinServ__FinancialAccount__c' ;
      finFinancialAccountTransactionObjName ='FinServ__FinancialAccountTransaction__c' ;
      productLoanRelationShipName = 'Finserv__FinancialAccountTranslations__r';
      productFeeRelationShipName = namespace + 'ProductFeesFSC__r';
    }else{
      finAccountObjName = baseNamespace+'FNS_FinancialAccount__c' ;
      finFinancialAccountTransactionObjName = baseNamespace+'FNS_FinancialAccountTransaction__c' ;
      productLoanRelationShipName = baseNamespace + 'FinancialAccountLoans__r';
      productFeeRelationShipName = baseNamespace + 'FinancialProductFees__r';
    }
    finAccountObject = Schema.getGlobalDescribe().get(finAccountObjName);
    finFinancialAccountTransactionObject = Schema.getGlobalDescribe().get(finFinancialAccountTransactionObjName);
    uow = new fflib_SObjectUnitOfWork( 
      new Schema.SObjectType[] {
        Opportunity.SObjectType,
        finAccountObject, 
        FNS_Pricing__c.SObjectType,
        FNS_Fee__c.SObjectType,
        finFinancialAccountTransactionObject
      }
    ); */
  } 
   /*************************************************************************************
     * @description  Constructs the domain class for Opportunity.
     * @Params       set of Opportunity ID
     * @Returns      none
     **************************************************************************************/
    
    public static void getSummaryForLoanAndFees(Set<ID> oppSet){
       /* List<Opportunity>  oppWithProductList;
        Map<String,Opportunity> productWithOpportunity = new Map<String,Opportunity>();
       
        Set<ID> productIDSet = new Set<ID>();
        String productRelationshipName;
        String loanAmount;
        String feeAmount; 
    
        if(FNS_Util.isFSCInstalled){
            productRelationshipName = extNamespace+'FinancialAccountApplicationsFSC__r';
            loanAmount = extNamespace + 'FinServ__Amount__c';
            feeAmount = extNamespace +'FNS_Amount__c';
         
        }else{
            productRelationshipName = baseNamespace+'FinancialAccountApplications__r';
            loanAmount = baseNamespace + 'FNS_Amount__c';
            feeAmount = baseNamespace +'FNS_Amount__c';
        }

        ID oppReadOnlyID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(FNS_Constants.OPPORTUNITY_READONLYRECORDTYPE).RecordTypeId ;
        
        if(oppSet != null && !oppSet.isEmpty()){
            oppWithProductList = new FNS_ApplicationSelector().selectApplicationWithProducts(oppSet);
            if(oppWithProductList != null && !oppWithProductList.isEmpty()){
                for (Opportunity opp : oppWithProductList){
                    if(opp.RecordTypeId != oppReadOnlyID){
                        for(Sobject obj :opp.getsObjects(productRelationshipName)){
                            productIDSet.add(obj.Id);
                            productWithOpportunity.put(obj.Id ,opp);
                        }
                    }
                }
            }
        }
        Set<ID> oppIDsReset = new Set<ID>();
        if(!productIDSet.isEmpty()){
            List<Sobject> productWithRelatedRecList =   new FNS_ProductsSelector().selectProductsWithChilds(productIDSet);
            if(productWithRelatedRecList != null && !productWithRelatedRecList.isEmpty()){
                for (Sobject productObj : productWithRelatedRecList ){
                        opportunity opp;
                        if(productWithOpportunity.containsKey(productObj.id)){  
                            opp = productWithOpportunity.get(productObj.id);                     
                                opp.FNS_LoanAmount__c = 0;
                                opp.FNS_Fees__c  = 0;
                                oppIDsReset.add(opp.Id);
                        }
                    
                    for(Sobject loanObj : productObj.getsObjects(productLoanRelationShipName)){
                        if(opp != null){
                            opp.FNS_LoanAmount__c = opp.FNS_LoanAmount__c + Integer.valueOF( loanObj.get(loanAmount));
                        }
                    }
        
                    for(Sobject feeObj : productObj.getsObjects(productFeeRelationShipName)){
                        if(opp != null){
                            opp.FNS_Fees__c  = opp.FNS_Fees__c   + Integer.valueOF(feeObj.get(feeAmount));
                        }
                    }
                   
                    uow.registerDirty(opp);
                }
            }
        }
       
        FNS_ObjectAccessContainer.checkOpportunityAccess(FNS_AccessController.DML_OPERATION_UPDATE);
        uow.commitWork(); 
       */

    }

    /************************************************************************************************************
    * @description  This methods is used to calculate rollup amount of all associated product on application.
    * @Params       set of opportunity ID
    * @Returns      none
    ************************************************************************************************************/
    
    public static void setProductRollUpAmountOnProduct(Set<ID> oppSet){
        List<Opportunity>  oppWithProductList;
        String productRelationshipName;
        String prodAmountField;
    
        if(FNS_Util.isFSCInstalled){
            productRelationshipName = extNamespace+'FinancialAccountApplicationsFSC__r';
			prodAmountField = extNamespace+'FNS_Amount__c';
        }else{
            productRelationshipName = baseNamespace+'FinancialAccountApplications__r';
			prodAmountField = baseNamespace+'FNS_Amount__c';
        }
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork( 
				new Schema.SObjectType[] {
					Opportunity.SObjectType
				}
        );
        if(oppSet != null && !oppSet.isEmpty()){
            oppWithProductList = new FNS_ApplicationSelector().selectApplicationWithProducts(oppSet);
            if(oppWithProductList != null && !oppWithProductList.isEmpty()){
                for (Opportunity opp : oppWithProductList){
				        opp.FNS_TotalRequestedAmount__c =0;
                        for(Sobject obj :opp.getsObjects(productRelationshipName)){
                           opp.FNS_TotalRequestedAmount__c =  opp.FNS_TotalRequestedAmount__c + Integer.valueOF(obj.get(prodAmountField));
						   opp.FNS_BypassValidation__c = !opp.FNS_BypassValidation__c;
                        }
					uow.registerDirty(opp);
                }
            }
        }
        FNS_ObjectAccessContainer.checkOpportunityAccess(FNS_AccessController.DML_OPERATION_UPDATE);
        uow.commitWork(); 
    }
}