force-app/main/default/objects/FNS_Pricing__c/FNS_Pricing__c.object-meta.xml
<CustomObject>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
 	<displayFormat>PN -{0000}</displayFormat>     
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_AllInRate__c.field-meta.xml
<CustomField>
    <fullName>FNS_AllInRate__c</fullName>
    <label>All In Rate</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_BaseRate__c.field-meta.xml
<CustomField>
    <fullName>FNS_BaseRate__c</fullName>
    <label>Base Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_CalcType__c.field-meta.xml
<CustomField>
    <fullName>FNS_CalcType__c</fullName>
    <label>Calculation Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_Frequencies__c.field-meta.xml
<CustomField>
    <fullName>FNS_Frequencies__c</fullName>
    <label>Frequencies</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_PricingType__c.field-meta.xml
<CustomField>
    <fullName>FNS_PricingType__c</fullName>
    <label>Pricing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_PricingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_RateBasis__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateBasis__c</fullName>
    <label>Rate Basis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_RateType__c.field-meta.xml
<CustomField>
    <fullName>FNS_RateType__c</fullName>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Variable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/fields/FNS_Spread__c.field-meta.xml
<CustomField>
    <fullName>FNS_Spread__c</fullName>
    <label>Spread</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Pricing__c/recordTypes/FNS_Pricing.recordType-meta.xml
<RecordType>
    <fullName>FNS_Pricing</fullName>
    <active>true</active>
    <label>Pricing</label>
</RecordType>

force-app/main/default/globalValueSets/FNS_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_PricingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>PricingType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_PricingDomain.cls
/**
 * Copyright (c) 2019, Brillio
 * All rights reserved.
 * @author Brillio
 * @date 2019
 * @group Domain Class
 * @description This class act as a domain class for Pricing object.
 */  
public with sharing class FNS_PricingDomain {

	/*************************************************************************************
	 * @description  Method to convert JSON Response into Pricing object.
	 * @Params       Namespace as string
	 * @Params       Financial Account as sObject
	 * @Params       Pricing wrapper class object
	 * @Returns      Pricing object.
	 *************************************************************************************/
	public static FNS_Pricing__c assignJSONToPricing(String namespace ,SObject finAccount ,FNS_ObjectContainer.FNS_Pricing pricingRec){
		FNS_Pricing__c pricing = new FNS_Pricing__c();
		FNS_ErrorLog logger = new FNS_ErrorLog();
		try{
			pricing.FNS_AllInRate__c = pricingRec.allInRate;//UI pricing type
			if(pricingRec.baseRate != null ){
				pricing.FNS_BaseRate__c = Decimal.valueof(pricingRec.baseRate);
			}
			pricing.FNS_CalcType__c = pricingRec.calcType;
			pricing.FNS_Frequencies__c = pricingRec.frequency;
			pricing.FNS_PricingType__c = pricingRec.pricingType;
			pricing.FNS_RateBasis__c = pricingRec.rateBasis;        
			pricing.FNS_RateType__c = pricingRec.rateType;
			pricing.FNS_Spread__c = pricingRec.spread;
		}catch(Exception ex){
            logger.addLogRecord('FNS_PricingDomain', 'assignJSONToPricing', ex.getMessage() + ex.getStackTraceString());
        }
		return pricing;
	} 
}