force-app/main/default/objects/FNS_Collateral__c/FNS_Collateral__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Collateral details.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralCategory__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralCategory__c</fullName>
    <label>Collateral Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_CollateralCategoryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralType__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralType__c</fullName>
    <description>This field is used to store collateral type values.</description>
    <label>Collateral Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_CollateralType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FNS_CollateralCategoryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>7059</fullName>
        <label>Securities</label>
    </customValue>
    <customValue>
        <fullName>6458</fullName>
        <label>Real Estate</label>
    </customValue>
    <customValue>
        <fullName>Type 3</fullName>
        <isActive>false</isActive>
        <label>Type 3</label>
    </customValue>
    <description>This value set is used to map collateral category type.</description>
    <masterLabel>CollateralCategoryType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_CollateralControllerTest.cls
public class FNS_CollateralControllerTest {
    
    @AuraEnabled
    public static List <FNS_Collateral__c> fetchCollateralData() {
        //Qyery 10 accounts
        List<FNS_Collateral__c> collateralList = [SELECT FNS_Application__r.name, FNS_Application__c,FNS_CollateralCategory__c,FNS_CollateralType__c FROM FNS_Collateral__c WHERE FNS_Application__c !=null];
        //return list of accounts
        return collateralList;
    }

}