force-app/main/default/objects/FNS_Collateral__c/FNS_Collateral__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Collateral details.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_AccountNumber__c</fullName>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_AgricultureUse__c.field-meta.xml
<CustomField>
    <fullName>FNS_AgricultureUse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agricultural Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Amount__c.field-meta.xml
<CustomField>
    <fullName>FNS_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_AppraisalDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_AppraisalDate__c</fullName>
    <description>This field is usedes to  map Appraisa lDate from API.</description>
    <label>Appraisal / Valuation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_AppraisalRequired__c.field-meta.xml
<CustomField>
    <fullName>FNS_AppraisalRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to map appraisal Required field fromAPI.</description>
    <label>Appraisal Report Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_AppraisalTypeId__c.field-meta.xml
<CustomField>
    <fullName>FNS_AppraisalTypeId__c</fullName>
    <label>Appraisal Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_BookNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_BookNumber__c</fullName>
    <label>Book Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CensusTract__c.field-meta.xml
<CustomField>
    <fullName>FNS_CensusTract__c</fullName>
    <label>Tract</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralAddress__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral Address</label>
    <referenceTo>FNS_Address__c</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralCategory__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralCategory__c</fullName>
    <label>Collateral Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_CollateralCategoryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralExtId__c</fullName>
    <description>This field is used as External id field.</description>
    <label>Collateral Ext Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralNumber__c</fullName>
    <description>This field is used to map collateralNumber field.</description>
    <label>Collateral Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralOwner__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralType__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralType__c</fullName>
    <description>This field is used to store collateral type values.</description>
    <label>Collateral Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_CollateralType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Description__c.field-meta.xml
<CustomField>
    <fullName>FNS_Description__c</fullName>
    <description>This field is used to store description value for collateral.</description>
    <label>Collateral Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_HostNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_HostNumber__c</fullName>
    <description>This field is used to map hostNumber field.</description>
    <label>Host Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_IssuerName__c.field-meta.xml
<CustomField>
    <fullName>FNS_IssuerName__c</fullName>
    <label>Issuer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_LegalDescription__c.field-meta.xml
<CustomField>
    <fullName>FNS_LegalDescription__c</fullName>
    <label>Legal Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_NumberOfUnits__c.field-meta.xml
<CustomField>
    <fullName>FNS_NumberOfUnits__c</fullName>
    <label>Numb. Of Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_OwnerOccupied__c.field-meta.xml
<CustomField>
    <fullName>FNS_OwnerOccupied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Owner Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PageNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_PageNumber__c</fullName>
    <label>Page Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Parcel__c.field-meta.xml
<CustomField>
    <fullName>FNS_Parcel__c</fullName>
    <label>Parcel ID#</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PercentLeased__c.field-meta.xml
<CustomField>
    <fullName>FNS_PercentLeased__c</fullName>
    <label>Percent Leased</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PledgedDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_PledgedDate__c</fullName>
    <label>Pledged Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PropertyBuiltDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_PropertyBuiltDate__c</fullName>
    <label>Date Property Built</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PropertyContactEmail__c.field-meta.xml
<CustomField>
    <fullName>FNS_PropertyContactEmail__c</fullName>
    <label>Property Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PropertyContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>FNS_PropertyContactFirstName__c</fullName>
    <label>Property Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PropertyContactLastName__c.field-meta.xml
<CustomField>
    <fullName>FNS_PropertyContactLastName__c</fullName>
    <label>Property Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PropertyDescription__c.field-meta.xml
<CustomField>
    <fullName>FNS_PropertyDescription__c</fullName>
    <label>Property Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PropertyIdNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_PropertyIdNumber__c</fullName>
    <label>Property ID Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_PurchaseDate__c</fullName>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_PurchasedDate__c</fullName>
    <description>This field is used to map purchasedDate from API..</description>
    <label>Date Purchased</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_RecordingOffice__c.field-meta.xml
<CustomField>
    <fullName>FNS_RecordingOffice__c</fullName>
    <label>Recording Office</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_SecurityType__c.field-meta.xml
<CustomField>
    <fullName>FNS_SecurityType__c</fullName>
    <label>Security Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_CollateralCategoryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_SpecifiedGuidelines__c.field-meta.xml
<CustomField>
    <fullName>FNS_SpecifiedGuidelines__c</fullName>
    <label>Specified Guidelines</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_SquareFootage__c.field-meta.xml
<CustomField>
    <fullName>FNS_SquareFootage__c</fullName>
    <label>Square Footage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_StockSymbol__c.field-meta.xml
<CustomField>
    <fullName>FNS_StockSymbol__c</fullName>
    <label>Stock Symbol</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Subdivision__c.field-meta.xml
<CustomField>
    <fullName>FNS_Subdivision__c</fullName>
    <label>Subdivision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_TaxMapNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_TaxMapNumber__c</fullName>
    <label>Tax Map#</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_ValueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_ValueDate__c</fullName>
    <label>Source Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_ValueFairMarket__c.field-meta.xml
<CustomField>
    <fullName>FNS_ValueFairMarket__c</fullName>
    <label>Source of Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_ValueSource__c.field-meta.xml
<CustomField>
    <fullName>FNS_ValueSource__c</fullName>
    <label>Value Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/FNS_CollateralCategoryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>7059</fullName>
        <label>Securities</label>
    </customValue>
    <customValue>
        <fullName>6458</fullName>
        <label>Real Estate</label>
    </customValue>
    <customValue>
        <fullName>Type 3</fullName>
        <isActive>false</isActive>
        <label>Type 3</label>
    </customValue>
    <description>This value set is used to map collateral category type.</description>
    <masterLabel>CollateralCategoryType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_CollateralSelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on FNS_Collateral__c object
****************************************************************************************/
public with sharing class FNS_CollateralSelector extends fflib_SObjectSelector{

    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/
    public FNS_CollateralSelector() {
        super(true, true, true);
    }
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/
    public FNS_CollateralSelector(Boolean enforceFLS) {
        super(true, true, false);
    }
    
    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of FNS_Collateral__c object
        * @param 	   none
        * @return      List of Schema.SObjectField of FNS_Collateral__c object
    **************************************************************************************/ 
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> { 
            FNS_Collateral__c.Id,
            FNS_Collateral__c.FNS_AccountNumber__c,
			FNS_Collateral__c.FNS_ValueDate__c,
			FNS_Collateral__c.FNS_AgricultureUse__c,
			FNS_Collateral__c.FNS_Amount__c,
			FNS_Collateral__c.FNS_Application__c,
			FNS_Collateral__c.FNS_AppraisalDate__c,
			FNS_Collateral__c.FNS_AppraisalRequired__c,
			FNS_Collateral__c.FNS_AppraisalTypeId__c,
			FNS_Collateral__c.FNS_BookNumber__c,
			FNS_Collateral__c.FNS_CollateralAddress__c,
			FNS_Collateral__c.FNS_CollateralCategory__c,
			FNS_Collateral__c.FNS_CollateralExtId__c,
			FNS_Collateral__c.FNS_CollateralNumber__c,	
			FNS_Collateral__c.FNS_CollateralOwner__c,	
			FNS_Collateral__c.FNS_CollateralType__c,
			FNS_Collateral__c.FNS_PropertyBuiltDate__c,
			FNS_Collateral__c.FNS_Description__c,
			FNS_Collateral__c.FNS_HostNumber__c,
			FNS_Collateral__c.FNS_IssuerName__c,
			FNS_Collateral__c.FNS_LegalDescription__c,	
			FNS_Collateral__c.FNS_NumberOfUnits__c,
			FNS_Collateral__c.FNS_OwnerOccupied__c,	
			FNS_Collateral__c.FNS_PageNumber__c,	
			FNS_Collateral__c.FNS_Parcel__c,
			FNS_Collateral__c.FNS_PercentLeased__c,
			FNS_Collateral__c.FNS_PledgedDate__c,
			FNS_Collateral__c.FNS_PropertyContactEmail__c,
			FNS_Collateral__c.FNS_PropertyContactFirstName__c,	
			FNS_Collateral__c.FNS_PropertyContactLastName__c,	
			FNS_Collateral__c.FNS_PropertyDescription__c,	
			FNS_Collateral__c.FNS_PropertyIdNumber__c,	
			//FNS_Collateral__c.FNS_ProposedUse__c,
			FNS_Collateral__c.FNS_PurchaseDate__c,
			FNS_Collateral__c.FNS_PurchasedDate__c,
			FNS_Collateral__c.FNS_RecordingOffice__c,
			FNS_Collateral__c.FNS_SecurityType__c,
			FNS_Collateral__c.FNS_ValueSource__c,
			FNS_Collateral__c.FNS_ValueFairMarket__c,	
			FNS_Collateral__c.FNS_SpecifiedGuidelines__c,	
			FNS_Collateral__c.FNS_SquareFootage__c,
			FNS_Collateral__c.FNS_StockSymbol__c,	
			FNS_Collateral__c.FNS_Subdivision__c,
			FNS_Collateral__c.FNS_TaxMapNumber__c,
			FNS_Collateral__c.FNS_CensusTract__c
        };
    }
    
    /*************************************************************************************
        * @description Method to return SObject type of FNS_Collateral__c object
        * @param 	   none
        * @return      Returns SObjecttype of FNS_Collateral__c object
    **************************************************************************************/
    public Schema.SObjectType getSObjectType() {
        return FNS_Collateral__c.sObjectType;
    }
    
    public List<SObject> getCollateralById(Set<Id> collateralIdSet) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();

        fflib_QueryFactory collateralQueryFactory = newQueryFactory(true, true, true);
        collateralQueryFactory.assertIsAccessible();
        //collateralQueryFactory.setEnforceFLS(true);
        collateralQueryFactory.selectField('Id');
       
        String collQueryCondition; 
        if(collateralIdSet != null){
            collQueryCondition= 'Id IN :collateralIdSet';
            collateralQueryFactory.setCondition(collQueryCondition);
        }
        return (List<SObject>) Database.query(collateralQueryFactory.toSOQL());
    }     
    
}