force-app/main/default/objects/Activity/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <label>Application External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/FNS_DueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_DueDate__c</fullName>
    <label>Due Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/FNS_SLAIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_SLAIndicator__c</fullName>
    <label>SLA Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/FNS_SLAPercentage__c.field-meta.xml
<CustomField>
    <fullName>FNS_SLAPercentage__c</fullName>
    <label>SLA Percentage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/FNS_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity List</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ActivityExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityExternalId__c</fullName>
    <description>Activity Identifier</description>
    <externalId>true</externalId>
    <label>Activity External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ActivityNotes__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityNotes__c</fullName>
    <label>Activity Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <description>Application Id</description>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/FNS_ApplicationWithQueueActivity__c.object-meta.xml
<CustomObject>
    <label>Application With QueueActivity</label>
    <nameField>
        <label>ApplicationWithQueueActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications With QueueActivity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_Activity__c.field-meta.xml
<CustomField>
    <fullName>FNS_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>FNS_Activity__c</referenceTo>
    <relationshipLabel>Applications With QueueActivity</relationshipLabel>
    <relationshipName>Applications_With_QueueActivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ActivityExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityExternalId__c</fullName>
    <label>Activity External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ActivityNotes__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityNotes__c</fullName>
    <label>Activity Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications With QueueActivity</relationshipLabel>
    <relationshipName>Applications_With_QueueActivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationCloseDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationCloseDate__c</fullName>
    <formula>FNS_Application__r.CloseDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationDescription__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationDescription__c</fullName>
    <label>Application Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExternalId__c</fullName>
    <label>Application External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <formula>FNS_Application__r.FNS_ApplicationExtId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Ext Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationName__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationName__c</fullName>
    <formula>FNS_Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationQuip__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationQuip__c</fullName>
    <formula>FNS_Application__r.FNS_Quip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Quip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationStage__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationStage__c</fullName>
    <formula>Text(FNS_Application__r.StageName )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CompletedByUserId__c.field-meta.xml
<CustomField>
    <fullName>FNS_CompletedByUserId__c</fullName>
    <label>Completed By User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_CompletionDate__c</fullName>
    <label>Completion Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CompletionTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_CompletionTime__c</fullName>
    <label>Completion Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_Contact__c.field-meta.xml
<CustomField>
    <fullName>FNS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ApplicationsWithQueueActivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CreatedByUserId__c.field-meta.xml
<CustomField>
    <fullName>FNS_CreatedByUserId__c</fullName>
    <label>Created By User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CreationDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_CreationDate__c</fullName>
    <label>Creation Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_DueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_DueDate__c</fullName>
    <label>Due Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_DueTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_DueTime__c</fullName>
    <label>Due Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_GroupDueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_GroupDueDate__c</fullName>
    <label>Group Due Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_HostIdentifier__c.field-meta.xml
<CustomField>
    <fullName>FNS_HostIdentifier__c</fullName>
    <label>Host Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_IsCommunity__c.field-meta.xml
<CustomField>
    <fullName>FNS_IsCommunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Community</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_IsCurrentActivity__c.field-meta.xml
<CustomField>
    <fullName>FNS_IsCurrentActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_JobDueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_JobDueDate__c</fullName>
    <label>Job Due Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_LegalBookNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_LegalBookNumber__c</fullName>
    <label>Legal Book Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_NumberOfHours__c.field-meta.xml
<CustomField>
    <fullName>FNS_NumberOfHours__c</fullName>
    <label>Number of Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ProcessCenterId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessCenterId__c</fullName>
    <label>Process Center Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ProcessGroupId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessGroupId__c</fullName>
    <label>Process Group Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ProcessJobId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessJobId__c</fullName>
    <label>Process Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_QueueExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_QueueExternalId__c</fullName>
    <label>Queue External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_SlaIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_SlaIndicator__c</fullName>
    <label>Sla Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_SlaPercentage__c.field-meta.xml
<CustomField>
    <fullName>FNS_SlaPercentage__c</fullName>
    <label>Sla Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_StartDateTime__c</fullName>
    <label>Start Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_StartTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_StartTime__c</fullName>
    <label>Start Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_StopClockIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_StopClockIndicator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Clock Indicator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FNS_ApplicationWithQueueActivitySelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on ApplicationWithQueueActivity object
****************************************************************************************/
public with sharing class FNS_ApplicationWithQueueActivitySelector extends fflib_SObjectSelector {
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/
    public FNS_ApplicationWithQueueActivitySelector() {
        super(true, true, true);
    }
     
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/ 
    public FNS_ApplicationWithQueueActivitySelector(Boolean enforceFLS) {
        super(true, true, false);
    }
    
    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of 
        			   ApplicationWithQueueActivity object 
        * @param 	   none
        * @return      List of Schema.SObjectField of ApplicationWithQueueActivity
       		 		   object
    **************************************************************************************/
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            FNS_ApplicationWithQueueActivity__c.Id,
                FNS_ApplicationWithQueueActivity__c.FNS_ActivityExternalId__c,
                FNS_ApplicationWithQueueActivity__c.FNS_QueueExternalId__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_IsCurrentActivity__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_ActivityNotes__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_SequenceNumber__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_CompletedByUserId__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_CompletionDate__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_CompletionTime__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_CreatedByUserId__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_CreationDate__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_DueDate__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_DueTime__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_GroupDueDate__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_HostIdentifier__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_JobDueDate__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_LegalBookNumber__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_NumberOfHours__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_ProcessCenterId__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_ProcessGroupId__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_ProcessJobId__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_SlaIndicator__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_SlaPercentage__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_StartDateTime__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_StartTime__c, 
                FNS_ApplicationWithQueueActivity__c.FNS_StopClockIndicator__c,
                FNS_ApplicationWithQueueActivity__c.FNS_ApplicationExtId__c 
                };
    }
    
    /*************************************************************************************
        * @description Method to return SObject type of ApplicationWithQueueActivity
        			   object
        * @param 	   none
        * @return      Returns SObjecttype of ApplicationWithQueueActivity object
    **************************************************************************************/
    public Schema.SObjectType getSObjectType() {
        return FNS_ApplicationWithQueueActivity__c.sObjectType;
    }
    
    /*************************************************************************************
        * @description Method to return ApplicationWithQueueActivity records based on 
        			   queue Activity Ids
        * @param 	   Set of queue Activity ids
        * @return      Returns List of ApplicationWithQueueActivity object
    **************************************************************************************/
    public List<FNS_ApplicationWithQueueActivity__c> selectById(Set<Id> queueActivityIds) {
        return (List<FNS_ApplicationWithQueueActivity__c>) selectSObjectsById(queueActivityIds);
    }
    
    /*************************************************************************************
        * @description Method to return ApplicationWithQueueActivity records
        * @param 	   none
        * @return      Returns List of ApplicationWithQueueActivity object
    **************************************************************************************/
    public List<FNS_ApplicationWithQueueActivity__c> getAllqueueActivities() {
        return Database.query(newQueryFactory().toSOQL());
    }
    
    /*************************************************************************************
        * @description Method to return ApplicationWithQueueActivity records based on 
                       Application ID 
        * @param       Set of Application Ids
        * @return      Returns List of ApplicationWithQueueActivity object
    **************************************************************************************/
    public List<FNS_ApplicationWithQueueActivity__c> getActivities(String appId) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        fflib_QueryFactory queueActivitiesQueryFactory = newQueryFactory(true, true, true);
        queueActivitiesQueryFactory.assertIsAccessible();
        queueActivitiesQueryFactory.setEnforceFLS(true);
        queueActivitiesQueryFactory.selectField('Id');
        
        String queueActivityQueryCondition; 
        if(appId != null){
            queueActivityQueryCondition= baseNamespace+'FNS_ApplicationExternalId__c=:appId'; 
            queueActivitiesQueryFactory.setCondition(queueActivityQueryCondition);
        }
        return (List<FNS_ApplicationWithQueueActivity__c>) Database.query(queueActivitiesQueryFactory.toSOQL());
    }
    
    /*************************************************************************************
        * @description Method to return ApplicationWithQueueActivity records based on 
                       Activity Ids and Application ID
        * @param       Set of Activity Ids
        * @param       Set of Application Ids
        * @return      Returns List of ApplicationWithQueueActivity object
    **************************************************************************************/
    public List<FNS_ApplicationWithQueueActivity__c> getActivitiesRecords(String activityId, String appId) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        fflib_QueryFactory queueActivitiesQueryFactory = newQueryFactory(true, true, true);
        queueActivitiesQueryFactory.assertIsAccessible();
        queueActivitiesQueryFactory.setEnforceFLS(true);
        queueActivitiesQueryFactory.selectField('Id');
        queueActivitiesQueryFactory.selectField(baseNamespace+'FNS_ApplicationExternalId__c');
        
        List<String> queueActivityQueryConditions = new List<String>(); 
        if(appId != null && activityId != null){
            queueActivityQueryConditions.add(baseNamespace+'FNS_IsCurrentActivity__c= true');
            queueActivityQueryConditions.add(baseNamespace+'FNS_ApplicationExternalId__c=:appId');
            queueActivityQueryConditions.add(baseNamespace+'FNS_IsCommunity__c = false');             
            queueActivitiesQueryFactory.setCondition(String.join(queueActivityQueryConditions, ' AND '));
        }
        fflib_SObjectSelector activitySelector = new FNS_ActivitiesSelector();
        activitySelector.configureQueryFactoryFields(queueActivitiesQueryFactory, baseNamespace+'FNS_Activity__r');
        
        return (List<FNS_ApplicationWithQueueActivity__c>) Database.query(queueActivitiesQueryFactory.toSOQL());
    }
    
    /*************************************************************************************
        * @description Method to return ApplicationWithQueueActivity records based on 
        			   Activity Ids 
		* @param 	   Set of Activity Ids
        * @return      Returns List of ApplicationWithQueueActivity object
    **************************************************************************************/
    public List<FNS_ApplicationWithQueueActivity__c> getActivitiesWithApplication(String appId) {
        String baseNamespace= FNS_Util.getBasePackageNamepace(); 
        fflib_QueryFactory queueActivitiesQueryFactory = newQueryFactory(true, true, true);
        queueActivitiesQueryFactory.assertIsAccessible();
        queueActivitiesQueryFactory.setEnforceFLS(true);
        queueActivitiesQueryFactory.selectField('Id');
        queueActivitiesQueryFactory.selectField(baseNamespace+'FNS_ActivityExternalId__c');
        queueActivitiesQueryFactory.selectField(baseNamespace+'FNS_QueueExternalId__c');
        queueActivitiesQueryFactory.selectField(baseNamespace+'FNS_ApplicationExternalId__c');
        queueActivitiesQueryFactory.selectField(baseNamespace+'FNS_ActivityNotes__c');
        queueActivitiesQueryFactory.selectField(baseNamespace+'FNS_IsCurrentActivity__c');
        
        List<String> queueActivityQueryConditions = new List<String>(); 
        if(appId != null){
            queueActivityQueryConditions.add(baseNamespace+'FNS_ApplicationExternalId__c=:appId'); 
            queueActivityQueryConditions.add(baseNamespace+'FNS_IsCommunity__c = false'); 
            queueActivitiesQueryFactory.setCondition(String.join(queueActivityQueryConditions, ' AND '));
        }
        
        queueActivitiesQueryFactory.setOrdering(baseNamespace+'FNS_CompletionDate__c', fflib_QueryFactory.SortOrder.DESCENDING, true );
        return (List<FNS_ApplicationWithQueueActivity__c>) Database.query(queueActivitiesQueryFactory.toSOQL());
    }
    
    public List<FNS_ApplicationWithQueueActivity__c> getActivitiesByApp(Set<id> oppIdSet) {
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('FNS_ApplicationCloseDate__c');
        query.selectField('FNS_ApplicationStage__c');
        query.selectField('FNS_ApplicationExtId__c');
        query.selectField('FNS_Application__c');
        query.selectField('FNS_Contact__c');
        List<String> oppQueryConditions = new List<String>();
        if(oppIdSet != null && !oppIdSet.isEmpty()){
            oppQueryConditions.add('FNS_Application__c IN :oppIdSet');
        }
        
        if(! oppQueryConditions.isEmpty()){
            query.setCondition(String.join(oppQueryConditions, ' AND '));
        }
        return (List<FNS_ApplicationWithQueueActivity__c>) Database.query(query.toSOQL());
    }
    /*************************************************************************************
        * @description Method to return ApplicationWithQueueActivity records based on 
                       Contact ID 
        * @param       Contact Id
        * @return      Returns List of ApplicationWithQueueActivity object
    **************************************************************************************/
    public List<FNS_ApplicationWithQueueActivity__c> getActivitiesfromContact(String contactId) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        fflib_QueryFactory queueActivitiesQueryFactory = newQueryFactory(true, true, true);
        queueActivitiesQueryFactory.assertIsAccessible();
        queueActivitiesQueryFactory.setEnforceFLS(true);
        queueActivitiesQueryFactory.selectField('Id');
        queueActivitiesQueryFactory.selectField('FNS_ApplicationCloseDate__c');
        queueActivitiesQueryFactory.selectField('FNS_ApplicationName__c');
        queueActivitiesQueryFactory.selectField('FNS_ApplicationQuip__c');
        queueActivitiesQueryFactory.selectField('FNS_ApplicationStage__c');
        queueActivitiesQueryFactory.selectField('FNS_ApplicationDescription__c');
        List<String> queueActivityQueryCondition = new List<String>(); 
        if(contactId != null){
            queueActivityQueryCondition.add(baseNamespace+'FNS_Contact__c=:contactId'); 
            queueActivityQueryCondition.add(baseNamespace+'FNS_IsCommunity__c = true'); 
            queueActivityQueryCondition.add(baseNamespace+'FNS_ApplicationExtId__c != null');
            queueActivitiesQueryFactory.setCondition(String.join(queueActivityQueryCondition, ' AND '));
        }
        return (List<FNS_ApplicationWithQueueActivity__c>) Database.query(queueActivitiesQueryFactory.toSOQL());
    }
    
    /*****************************************************************************************************
        * @description Method to return ApplicationWithQueueActivity records based on Application Ids 
        * @param       Set of Application Ids
        * @return      Returns List of ApplicationWithQueueActivity object
    **********************************************************************************************************/
    public List<FNS_ApplicationWithQueueActivity__c> getActivitiesByApplication(Set<id> appIdSet) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('FNS_ApplicationCloseDate__c');
        query.selectField('FNS_ApplicationStage__c');
        query.selectField('FNS_ApplicationExtId__c');
        query.selectField('FNS_Application__c');
        query.selectField('FNS_Contact__c');
        List<String> oppQueryConditions = new List<String>();
        if(appIdSet != null && !appIdSet.isEmpty()){
            oppQueryConditions.add(baseNamespace+'FNS_Application__c IN :appIdSet');
             oppQueryConditions.add(baseNamespace+'FNS_IsCommunity__c = true'); 
        }
        
        if(! oppQueryConditions.isEmpty()){
            query.setCondition(String.join(oppQueryConditions, ' AND '));
        }
        return (List<FNS_ApplicationWithQueueActivity__c>) Database.query(query.toSOQL());
    }

}