force-app/main/default/objects/Activity/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <label>Application External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/FNS_DueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_DueDate__c</fullName>
    <label>Due Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/FNS_SLAIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_SLAIndicator__c</fullName>
    <label>SLA Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/FNS_SLAPercentage__c.field-meta.xml
<CustomField>
    <fullName>FNS_SLAPercentage__c</fullName>
    <label>SLA Percentage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/FNS_Activity__c.object-meta.xml
<CustomObject>
    <description>Activity List</description>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ActivityExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityExternalId__c</fullName>
    <description>Activity Identifier</description>
    <externalId>true</externalId>
    <label>Activity External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ActivityNotes__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityNotes__c</fullName>
    <label>Activity Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <description>Application Id</description>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Activity__c/fields/FNS_SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_SequenceNumber__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/FNS_ApplicationWithQueueActivity__c.object-meta.xml
<CustomObject>
    <label>Application With QueueActivity</label>
    <nameField>
        <label>ApplicationWithQueueActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications With QueueActivity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_Activity__c.field-meta.xml
<CustomField>
    <fullName>FNS_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>FNS_Activity__c</referenceTo>
    <relationshipLabel>Applications With QueueActivity</relationshipLabel>
    <relationshipName>Applications_With_QueueActivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ActivityExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityExternalId__c</fullName>
    <label>Activity External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ActivityNotes__c.field-meta.xml
<CustomField>
    <fullName>FNS_ActivityNotes__c</fullName>
    <label>Activity Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExternalId__c</fullName>
    <label>Application External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <formula>FNS_Application__r.FNS_ApplicationExtId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Ext Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CompletedByUserId__c.field-meta.xml
<CustomField>
    <fullName>FNS_CompletedByUserId__c</fullName>
    <label>Completed By User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_CompletionDate__c</fullName>
    <label>Completion Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CompletionTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_CompletionTime__c</fullName>
    <label>Completion Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CreatedByUserId__c.field-meta.xml
<CustomField>
    <fullName>FNS_CreatedByUserId__c</fullName>
    <label>Created By User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_CreationDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_CreationDate__c</fullName>
    <label>Creation Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_DueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_DueDate__c</fullName>
    <label>Due Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_DueTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_DueTime__c</fullName>
    <label>Due Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_GroupDueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_GroupDueDate__c</fullName>
    <label>Group Due Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_HostIdentifier__c.field-meta.xml
<CustomField>
    <fullName>FNS_HostIdentifier__c</fullName>
    <label>Host Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_IsCurrentActivity__c.field-meta.xml
<CustomField>
    <fullName>FNS_IsCurrentActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Activity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_JobDueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_JobDueDate__c</fullName>
    <label>Job Due Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_LegalBookNumber__c.field-meta.xml
<CustomField>
    <fullName>FNS_LegalBookNumber__c</fullName>
    <label>Legal Book Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_NumberOfHours__c.field-meta.xml
<CustomField>
    <fullName>FNS_NumberOfHours__c</fullName>
    <label>Number of Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ProcessCenterId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessCenterId__c</fullName>
    <label>Process Center Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ProcessGroupId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessGroupId__c</fullName>
    <label>Process Group Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_ProcessJobId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProcessJobId__c</fullName>
    <label>Process Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_QueueExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_QueueExternalId__c</fullName>
    <label>Queue External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_SlaIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_SlaIndicator__c</fullName>
    <label>Sla Indicator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_SlaPercentage__c.field-meta.xml
<CustomField>
    <fullName>FNS_SlaPercentage__c</fullName>
    <label>Sla Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_StartDateTime__c</fullName>
    <label>Start Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_StartTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_StartTime__c</fullName>
    <label>Start Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_StopClockIndicator__c.field-meta.xml
<CustomField>
    <fullName>FNS_StopClockIndicator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Clock Indicator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FNS_ApplicationWithQueueActivity__c/fields/FNS_User__c.field-meta.xml
<CustomField>
    <fullName>FNS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApplicationsWithQueueActivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_ApplicationExtId__c.field-meta.xml
<CustomField>
    <fullName>FNS_ApplicationExtId__c</fullName>
    <externalId>true</externalId>
    <label>CME Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>FNS_StartDateTime__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/FNS_UserExternalId__c.field-meta.xml
<CustomField>
    <fullName>FNS_UserExternalId__c</fullName>
    <externalId>true</externalId>
    <label>User External Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FNS_ApplicationWithQueueActivityDomain.cls
/**
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Activities
* @description This class is used to get activity data from CME  
*/
public with sharing class FNS_ApplicationWithQueueActivityDomain {
    
    static FNS_ErrorLog logger = new FNS_ErrorLog();
    
    /*************************************************************************************
    * @description  Method to get all activites based on CME applicationId
    * @Params       application Record 
    * @Returns      response String 
    **************************************************************************************/
    public static HttpResponse getActivitiesForApplication(String applicationExternalId){
        String responseStatus = FNS_Constants.STR_FAILURE; 
        HttpResponse jsonResponse;
        List<FNS_ApplicationWithQueueActivity__c> queueActivityObjList = new List<FNS_ApplicationWithQueueActivity__c>();
        List<String> activityIds = new List<String>(); 
        
        
        String response; 
        try{
            FNS_IntegrationUtil.FNS_RequestParam param = new FNS_IntegrationUtil.FNS_RequestParam();
            param.objectName = FNS_Constants.CLASS_QUEUE_ACTIVITIES;
            param.endPoint = FNS_Constants.URL_APPLICATION;
            param.methodName = FNS_Constants.METHOD_GET;
            param.extendedAPIUrl =  applicationExternalId + FNS_Constants.URL_QUEUE_ACTIVITIES_BY_APPLICATION;
          
            param.bypassBackSlash = true; 
            Map<String, String> headerMap = new Map<String, String>();
            headerMap.put(FNS_Constants.CONTENT_TYPE, FNS_Constants.CONTENT_TYPE_URLENCODED);        
            param.headerMap = headerMap;
            
            FNS_JSONAPIRouter router = new FNS_JSONAPIRouter();
            jsonResponse = router.getPostRequest(param);
        }
        catch (Exception ex){
            logger.addLogRecord('FNS_ApplicationWithQueueActivityDomain', 'getActivitiesForApplication', ex.getMessage() + ex.getStackTraceString()); 
        }      
        return jsonResponse;
    }
    
   /*************************************************************************************
    * @description  Method to handle Queue Activity Response 
    * @Params       HTTPResponse 
    * @Returns      null
    **************************************************************************************/
    public static void handleQueueActivityResponse(HTTPResponse jsonResponse){
        List<FNS_ApplicationWithQueueActivity__c> queueActivityObjList = new List<FNS_ApplicationWithQueueActivity__c>();
        List<String> activityIds = new List<String>(); 
        FNS_ActivitiesSelector activitySelector = new FNS_ActivitiesSelector();
        Map<String, FNS_Activity__c> mapActivityRecords = new Map<String, FNS_Activity__c>();
        Integer currentSequenceNumber;
        String applicationExternalId; 
        if(jsonResponse.getStatusCode() == 200){
                if(!String.isEmpty(jsonResponse.getBody())){
       
                    //This Json response will have activities related to the application
                     //This Json response will have activities related to the application
                    // code commented for API 1.0 changes  Start >>>>
                    //List<FNS_ObjectContainer.FNS_QueueActivityRoute > applicationConfigList = (List<FNS_ObjectContainer.FNS_QueueActivityRoute >)JSON.deserialize(jsonResponse.getBody(), List<FNS_ObjectContainer.FNS_QueueActivityRoute >.class);
                    List<FNS_ObjectContainer.FNS_QueueActivityRoute > applicationConfigList ;
                    FNS_ObjectContainer listQueueActivity = (FNS_ObjectContainer)JSON.deserialize(jsonResponse.getBody(), FNS_ObjectContainer.class);
                    if(listQueueActivity != null && listQueueActivity.queueActivitiesList  != null)
                    {
                       applicationConfigList = listQueueActivity.queueActivitiesList ;
                    }
                    for(FNS_ObjectContainer.FNS_QueueActivityRoute  appConfig : applicationConfigList){
                        activityIds.add(appConfig.activityId); 
                    }

                    //Fetch list of configuration activity records based on the application activityIds
                    List<FNS_Activity__c> activityRecords = activitySelector.getActivitywithId(activityIds); 
                    for(FNS_Activity__c actRecord: activityRecords){
                        mapActivityRecords.put(actRecord.FNS_ActivityExternalId__c, actRecord);
                    }
                    for(FNS_ObjectContainer.FNS_QueueActivityRoute appConfig : applicationConfigList){
                      
                        if(appConfig.current != null && appConfig.current){                    
                            currentSequenceNumber = appConfig.sequenceNumber;  
                            applicationExternalId = appConfig.applicationId; 
                        }
                    }
                    //For each activity, map appropriate fields from the Config data
                    for(FNS_ObjectContainer.FNS_QueueActivityRoute appConfig : applicationConfigList){ 
                        FNS_ApplicationWithQueueActivity__c queueActivityObj = new FNS_ApplicationWithQueueActivity__c(); 
                        queueActivityObj.FNS_ApplicationExternalId__c = appConfig.applicationId;
                        queueActivityObj.FNS_QueueExternalId__c = appConfig.queueActivityId;
                        queueActivityObj.FNS_ActivityExternalId__c = appConfig.activityId; 
                        if(appConfig.current!= null){
                            queueActivityObj.FNS_IsCurrentActivity__c = appConfig.current;
                        }
                        else {
                            queueActivityObj.FNS_IsCurrentActivity__c = false; 
                        }
                        queueActivityObj.FNS_SequenceNumber__c = appConfig.sequenceNumber; 
                        queueActivityObj.FNS_CompletedByUserId__c = appConfig.completedByUserId; 
                        queueActivityObj.FNS_CompletionDate__c = appConfig.completionDate; 
                        queueActivityObj.FNS_CompletionTime__c = appconfig.completionTime; 
                        queueActivityObj.FNS_CreatedByUserId__c = appConfig.createdByUserId; 
                        queueActivityObj.FNS_CreationDate__c = appConfig.creationDate; 
                        queueActivityObj.FNS_DueDate__c = appConfig.dueDate; 
                        queueActivityObj.FNS_DueTime__c = appConfig.dueTime; 
                        queueActivityObj.FNS_GroupDueDate__c = appConfig.groupDueDate;
                        queueActivityObj.FNS_HostIdentifier__c = appConfig.hostSystemInternalIdentifier;
                        queueActivityObj.FNS_JobDueDate__c = appConfig.jobDueDate;
                        queueActivityObj.FNS_LegalBookNumber__c = appConfig.legalBookNumber; 
                        queueActivityObj.FNS_NumberOfHours__c = appConfig.numHours; 
                        queueActivityObj.FNS_ProcessCenterId__c = appConfig.processCenterId; 
                        queueActivityObj.FNS_ProcessGroupId__c = appConfig.processGroupId; 
                        queueActivityObj.FNS_ProcessJobId__c = appConfig.processJobId; 
                        queueActivityObj.FNS_SlaIndicator__c = appConfig.slaIndicator; 
                        queueActivityObj.FNS_SlaPercentage__c = Integer.valueOf(appConfig.slaPercentage.trim());
                        queueActivityObj.FNS_StartDateTime__c = appConfig.startDate; 
                        queueActivityObj.FNS_StartTime__c = appConfig.startTime; 
                        queueActivityObj.FNS_StopClockIndicator__c = appConfig.stopClockIndicator; 
                        queueActivityObj.FNS_ActivityNotes__c = appConfig.note;
                        
                        if(mapActivityRecords.get(appConfig.activityId) != null){
                            queueActivityObj.FNS_Activity__c = mapActivityRecords.get(appConfig.activityId).Id; 
                        }
                        if(queueActivityObj.FNS_ActivityExternalId__c != null){
                            queueActivityObjList.add(queueActivityObj);
                        }
                        
                        
                    }
                    //delete the existing activity records for an application and insert new activity records 
                    if(!queueActivityObjList.isEmpty()){
                        if(applicationExternalId != null){
                            FNS_ApplicationWithQueueActivitySelector queueActivitySelector = new FNS_ApplicationWithQueueActivitySelector(); 
                            List<FNS_ApplicationWithQueueActivity__c> allRecords = queueActivitySelector.getActivitiesWithApplication(applicationExternalId);
                            new FNS_ApplicationWithQueueActivityService().deleteRecords(allRecords);
                            new FNS_ApplicationWithQueueActivityService().insertRecords(queueActivityObjList);
                        }
                    }
                }
         }
    }

    /*************************************************************************************
* @description  To do put callout on submit button 
* @Params       ActivityId, USer, Notes, ApplicationRecord
* @Returns      reponse String
**************************************************************************************/
    public static void routeActivityForApplication(String dataActivityId, User datauser, String datanotes, Opportunity applicationRecord){
        FNS_ApplicationwithQueueActivity__c queueActivityObj = new FNS_ApplicationwithQueueActivity__c();
        List<FNS_ApplicationWithQueueActivity__c> queueActivityList = new List<FNS_ApplicationWithQueueActivity__c>();
        FNS_ObjectContainer.FNS_QueueActivityRoute wrap = new FNS_ObjectContainer.FNS_QueueActivityRoute();
        List<Opportunity> applicationList = new List<Opportunity>();
        HTTPResponse jsonRes;
        HttpResponse jsonResponse; 
         if(dataActivityId != null){
            wrap.activityId =dataActivityId;  
            wrap.note= datanotes;
       
            if(datauser.FNS_UserExternalId__c != null){
                wrap.userId = datauser.FNS_UserExternalId__c;
            }
            
            wrap.applicationId = applicationRecord.FNS_ApplicationExtId__c;
            wrap.current = true; 
            
            FNS_ApplicationwithQueueActivitySelector activtyselector = new FNS_ApplicationwithQueueActivitySelector();
            List<FNS_ApplicationwithQueueActivity__c> actList = activtyselector.getActivitiesRecords(dataActivityId, applicationRecord.FNS_ApplicationExtId__c);
        
            if(actList != null && !actList.isEmpty()){
                wrap.queueActivityId = String.valueOf(actList[0].FNS_QueueExternalId__c);
                wrap.sequenceNumber = Integer.valueOf(actList[0].FNS_Activity__r.FNS_SequenceNumber__c); 
                wrap.completedByUserId = actList[0].FNS_CompletedByUserId__c; 
                wrap.completionDate = actList[0].FNS_CompletionDate__c; 
                wrap.createdByUserId = actList[0].FNS_CreatedByUserId__c; 
                wrap.completionTime= actList[0].FNS_CompletionTime__c; 
                wrap.creationDate= actList[0].FNS_CreationDate__c; 
                wrap.dueDate = actList[0].FNS_DueDate__c; 
                wrap.dueTime = actList[0].FNS_DueTime__c; 
                wrap.groupDueDate =actList[0].FNS_GroupDueDate__c; 
                wrap.hostSystemInternalIdentifier = actList[0].FNS_HostIdentifier__c; 
                wrap.jobDueDate = actList[0].FNS_JobDueDate__c; 
                wrap.legalBookNumber = actList[0].FNS_LegalBookNumber__c; 
                wrap.numHours = actList[0].FNS_NumberOfHours__c; 
                wrap.processCenterId = actList[0].FNS_ProcessCenterId__c; 
                wrap.processGroupId = actList[0].FNS_ProcessGroupId__c; 
                wrap.processJobId = actList[0].FNS_ProcessJobId__c; 
                wrap.slaIndicator = actList[0].FNS_SlaIndicator__c; 
                wrap.slaPercentage = String.valueOf(actList[0].FNS_SlaPercentage__c); 
                wrap.startDate = actList[0].FNS_StartDateTime__c; 
                wrap.startTime = actList[0].FNS_StartTime__c; 
                wrap.stopClockIndicator = actList[0].FNS_StopClockIndicator__c; 

                //update user details and notes on the activity record 
                queueActivityObj.FNS_ActivityNotes__c = datanotes;
                queueActivityObj.FNS_User__c = dataUser.Id;  
                queueActivityObj.Id = actList[0].Id; 
                
                String jsonBody = json.serialize(wrap);
                FNS_IntegrationUtil.FNS_RequestParam param = new FNS_IntegrationUtil.FNS_RequestParam();
                param.objectName = FNS_Constants.CLASS_QUEUE_ACTIVITIES;
                param.endPoint = FNS_Constants.URL_QUEUE_ACTIVITIES;
                param.methodName = FNS_Constants.METHOD_PUT;
                param.extendedAPIUrl =  actList[0].FNS_QueueExternalId__c + '/' + FNS_Constants.URL_QUEUE_ACTIVITIES_ROUTE;
                param.body=jsonBody;
                Map<String, String> headerMap = new Map<String, String>();
                headerMap.put(FNS_Constants.CONTENT_TYPE, FNS_Constants.APPLICATION_JSON);        
                param.headerMap = headerMap;
                System.debug('>>>JSON:>>>>' + jsonBody);
                FNS_JSONAPIRouter router = new FNS_JSONAPIRouter();
                jsonResponse = router.getPostRequest(param);
                
                if(jsonResponse != null){
                    if(jsonResponse.getStatusCode() == 200){
                        if(queueActivityObj.Id !=null){
                            queueActivityList.add(queueActivityObj);
                            new FNS_ApplicationWithQueueActivityService().updateRecord(queueActivityList); 
                        } 
                    }
                }
            }
        }  
    }
}