force-app/main/default/objects/FNS_Address__c/FNS_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Account__c.field-meta.xml
<CustomField>
    <fullName>FNS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Address1__c.field-meta.xml
<CustomField>
    <fullName>FNS_Address1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Address2__c.field-meta.xml
<CustomField>
    <fullName>FNS_Address2__c</fullName>
    <description>Address Line 2</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Address3__c.field-meta.xml
<CustomField>
    <fullName>FNS_Address3__c</fullName>
    <description>Address Line 3</description>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_AddressType__c.field-meta.xml
<CustomField>
    <fullName>FNS_AddressType__c</fullName>
    <description>Address Type</description>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_City__c.field-meta.xml
<CustomField>
    <fullName>FNS_City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Collateral__c.field-meta.xml
<CustomField>
    <fullName>FNS_Collateral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral</label>
    <referenceTo>FNS_Collateral__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_CountryCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_CountryCode__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_PostalCode__c</fullName>
    <description>Postal Code</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_PostalCodeExtension__c.field-meta.xml
<CustomField>
    <fullName>FNS_PostalCodeExtension__c</fullName>
    <label>Postal Code Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_ProvinceCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_ProvinceCode__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_State__c.field-meta.xml
<CustomField>
    <fullName>FNS_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/FNS_Collateral__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Collateral details.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/FNS_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Province.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Province</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_AddressSelector.cls
/****************************************************************************************
  * Copyright (c) 2019, Brillio
  * All rights reserved.
  * @author Brillio
  * @date 2019
  * @group Object Selector
  * @description This class is used to Query on FNS_Address__c object
****************************************************************************************/
public with sharing class FNS_AddressSelector extends fflib_SObjectSelector{

    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   none
        * @return      none
    **************************************************************************************/
    public FNS_AddressSelector() {
        super(true, true, true);
    }
    
    /*************************************************************************************
        * @description Constructor to set boolean values to TRUE of Super class.We are 
                       setting includeFieldsetFields, enforceCRUD, enforceFLS in param 
                       constructor to TRUE
        * @param 	   Boolean variable for enforcing FLS
        * @return      none
    **************************************************************************************/
    public FNS_AddressSelector(Boolean enforceFLS) {
        super(true, true, false);
    }
    
    /*************************************************************************************
        * @description Method to return Schema.SObjectField list of FNS_Address__c object
        * @param 	   none
        * @return      List of Schema.SObjectField of FNS_Address__c object
    **************************************************************************************/ 
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> { 
            FNS_Address__c.Id,
            FNS_Address__c.FNS_Account__c,
            FNS_Address__c.FNS_Address1__c,
            FNS_Address__c.FNS_Address2__c,
            FNS_Address__c.FNS_Address3__c,
            FNS_Address__c.FNS_AddressType__c,
            FNS_Address__c.FNS_City__c,
            FNS_Address__c.FNS_CountryCode__c,
            FNS_Address__c.FNS_PostalCodeExtension__c,
            FNS_Address__c.FNS_PostalCode__c,
            FNS_Address__c.FNS_ProvinceCode__c,
            FNS_Address__c.FNS_State__c
        };
    }
    
    /*************************************************************************************
        * @description Method to return SObject type of FNS_Address__c object
        * @param 	   none
        * @return      Returns SObjecttype of FNS_Address__c object
    **************************************************************************************/
    public Schema.SObjectType getSObjectType() {
        return FNS_Address__c.sObjectType;
    }
    
    /*************************************************************************************
        * @description Method to return FNS_Address__c records based on accountIds
        * @param 	   Set of Account ids
        * @return      Returns List of FNS_Address__c object
    **************************************************************************************/
    public List<FNS_Address__c> selectAddressByCustomer(Set<Id> accountIds) {
        String baseNamespace= FNS_Util.getBasePackageNamepace();    
        fflib_QueryFactory addressQueryFactory = newQueryFactory(true, true, true);
        addressQueryFactory.assertIsAccessible();
        addressQueryFactory.setEnforceFLS(true);
        
        if(accountIds != null && !accountIds.isEmpty()){
            addressQueryFactory.setCondition(baseNamespace+'FNS_Account__c IN :accountIds');
        }

        return (List<FNS_Address__c>) Database.query(addressQueryFactory.toSOQL() );
    }
    
    /*************************************************************************************
        * @description Method to return FNS_Address__c records based on accountIds
        * @param 	   Set of Account ids
        * @return      Returns List of FNS_Address__c object
    **************************************************************************************/
    public List<FNS_Address__c> getCollateralAddressRecords(Set<Id> collateralIDSet){
		String baseNamespace= FNS_Util.getBasePackageNamepace();    
	    fflib_QueryFactory addressQueryFactory = newQueryFactory(true, true, true);
	    addressQueryFactory.assertIsAccessible();
	        addressQueryFactory.setEnforceFLS(true);
	        
	        if(collateralIDSet != null && !collateralIDSet.isEmpty()){
	            addressQueryFactory.setCondition(baseNamespace+'FNS_Collateral__c IN :collateralIDSet');
	        }
	        return (List<FNS_Address__c>) Database.query(addressQueryFactory.toSOQL() );
	}
}