force-app/main/default/objects/FNS_Address__c/FNS_Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Address1__c.field-meta.xml
<CustomField>
    <fullName>FNS_Address1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_City__c.field-meta.xml
<CustomField>
    <fullName>FNS_City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Collateral__c.field-meta.xml
<CustomField>
    <fullName>FNS_Collateral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral</label>
    <referenceTo>FNS_Collateral__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_CountryCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_CountryCode__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>FNS_PostalCode__c</fullName>
    <description>Postal Code</description>
    <label>Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_State__c.field-meta.xml
<CustomField>
    <fullName>FNS_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Street2__c.field-meta.xml
<CustomField>
    <fullName>FNS_Street2__c</fullName>
    <label>Street2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Address__c/fields/FNS_Street__c.field-meta.xml
<CustomField>
    <fullName>FNS_Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/FNS_Collateral__c.object-meta.xml
<CustomObject>
    <description>This object is used to store Collateral details.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaterals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_AppraisalDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_AppraisalDate__c</fullName>
    <description>This field is usedes to  map Appraisa lDate from API.</description>
    <label>Appraisal / Valuation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralCategory__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralCategory__c</fullName>
    <label>Collateral Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_CollateralCategoryType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_CollateralType__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralType__c</fullName>
    <description>This field is used to store collateral type values.</description>
    <label>Collateral Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FNS_CollateralType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_Description__c.field-meta.xml
<CustomField>
    <fullName>FNS_Description__c</fullName>
    <description>This field is used to store description value for collateral.</description>
    <label>Collateral Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PledgedDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_PledgedDate__c</fullName>
    <label>Pledged Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_PurchasedDate__c</fullName>
    <description>This field is used to map purchasedDate from API..</description>
    <label>Date Purchased</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_ValueDate__c.field-meta.xml
<CustomField>
    <fullName>FNS_ValueDate__c</fullName>
    <label>Source Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_ValueFairMarket__c.field-meta.xml
<CustomField>
    <fullName>FNS_ValueFairMarket__c</fullName>
    <label>Source of Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FNS_Collateral__c/fields/FNS_ValueSource__c.field-meta.xml
<CustomField>
    <fullName>FNS_ValueSource__c</fullName>
    <label>Value Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_CollateralCategoryFieldSetMapping__mdt/FNS_CollateralCategoryFieldSetMapping__mdt.object-meta.xml
<CustomObject>
    <description>This is used to map collateral categories with corresponding fieldset.</description>
    <label>Collateral Category FieldSet Mapping</label>
    <pluralLabel>Collateral Category FieldSet Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/FNS_CollateralCategoryFieldSetMapping__mdt/fields/FNS_CollateralCategory__c.field-meta.xml
<CustomField>
    <fullName>FNS_CollateralCategory__c</fullName>
    <label>Collateral Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_CollateralCategoryFieldSetMapping__mdt/fields/FNS_FieldSetName__c.field-meta.xml
<CustomField>
    <fullName>FNS_FieldSetName__c</fullName>
    <label>FieldSet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_CollateralDocument__c/FNS_CollateralDocument__c.object-meta.xml
<CustomObject>
    <label>Collateral Document</label>
    <nameField>
        <label>Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_CollateralDocument__c/fields/FNS_Collateral__c.field-meta.xml
<CustomField>
    <fullName>FNS_Collateral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral</label>
    <referenceTo>FNS_Collateral__c</referenceTo>
    <relationshipLabel>Csollateral Document</relationshipLabel>
    <relationshipName>Csollateral_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_CollateralDocument__c/fields/FNS_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>FNS_DocumentId__c</fullName>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_CollateralWithProduct__c/FNS_CollateralWithProduct__c.object-meta.xml
<CustomObject>
    <description>This is junction object between collateral and product.</description>
    <label>Collateral With Product</label>
    <nameField>
        <label>Collateral Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaterals With Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_CollateralWithProduct__c/fields/FNS_Collateral__c.field-meta.xml
<CustomField>
    <fullName>FNS_Collateral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral</label>
    <referenceTo>FNS_Collateral__c</referenceTo>
    <relationshipLabel>Collaterals With Products</relationshipLabel>
    <relationshipName>Collaterals_With_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_CollateralWithProduct__c/fields/FNS_Product__c.field-meta.xml
<CustomField>
    <fullName>FNS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>FNS_FinancialAccount__c</referenceTo>
    <relationshipLabel>Collaterals With Products</relationshipLabel>
    <relationshipName>CollateralsWithProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FNS_CollateralCategoryType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>7059</fullName>
        <label>Securities</label>
    </customValue>
    <customValue>
        <fullName>6458</fullName>
        <label>Real Estate</label>
    </customValue>
    <customValue>
        <fullName>Type 3</fullName>
        <isActive>false</isActive>
        <label>Type 3</label>
    </customValue>
    <description>This value set is used to map collateral category type.</description>
    <masterLabel>CollateralCategoryType</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FNS_State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FNS_CollateralCmpController.cls
public class FNS_CollateralCmpController {
    static FNS_ErrorLog logger = new FNS_ErrorLog();
    static Map<String, String> categoryToFieldSetMap = new Map<String, String>();
 	
   Static {
        categoryToFieldSetMap = getMapOfCategoryFieldSet();
    }
   
    @AuraEnabled
    public static FNS_ObjectFieldSetWrapper getComponentData(String applicationId){
        FNS_ObjectFieldSetWrapper wrapper = new FNS_ObjectFieldSetWrapper();
        
        FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper collateralBaseWrapper = new FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper();
        collateralBaseWrapper.fields = FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c','FNS_BaseCollateral');
        collateralBaseWrapper.moreFields=FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c','FNS_BaseCollateral');
        collateralBaseWrapper.objectName = 'FNS_Collateral__c';
        collateralBaseWrapper.requiredFields= FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c','FNS_BaseCollateral');
        collateralBaseWrapper.objectLabel='COLLATERAL';
        
        FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper addressWrapper = new FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper();
        addressWrapper.fields = FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Address__c','FNS_CollateralAddress');
        addressWrapper.moreFields=FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Address__c','FNS_CollateralAddress');
        addressWrapper.objectName = 'FNS_Address__c';
        addressWrapper.requiredFields= FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Address__c','FNS_CollateralAddress');
        addressWrapper.objectLabel='Address';
        
        FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper collateralTypeWrapper = new FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper();
        collateralTypeWrapper.fields = FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c','FNS_RealEstate');
        collateralTypeWrapper.moreFields=FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c','FNS_RealEstate');
        collateralTypeWrapper.objectName = 'FNS_Collateral__c';
        collateralTypeWrapper.requiredFields= FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c','FNS_RealEstate');
        collateralTypeWrapper.objectLabel='COLLATERAL';
        
        wrapper.collateralBaseWrapper = collateralBaseWrapper;
        wrapper.addressWrapper = addressWrapper;
        wrapper.collateralTypeWrapper = collateralTypeWrapper;
        //wrapper.sObjectList = getColateralsByApplicationId(applicationId);
        system.debug('wrapper>>>>'+wrapper);
        return wrapper;
    }
        
    public static Map<String, String> getMapOfCategoryFieldSet(){
        Map<String, String> categoryFieldSetMapping = new Map<String, String>();
        List<FNS_CollateralCategoryFieldSetMapping__mdt> categoryFieldSetList = new FNS_CollateralCategoryMappingSelector().getAllRecords();
        for (FNS_CollateralCategoryFieldSetMapping__mdt mdtobj : categoryFieldSetList){
            categoryFieldSetMapping.put(mdtobj.FNS_CollateralCategory__c,mdtobj.FNS_FieldSetName__c);
        }
        return categoryFieldSetMapping;
    }
    
    @AuraEnabled
    public static FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper getComponentDataFromType(String categoryName){
        String fieldSetName;
        system.debug('@@ categoryName ' + categoryName);
        if(categoryName == null) {
                categoryName ='Real Estate';
        } 
        fieldSetName =  categoryToFieldSetMap.get(categoryName);
        FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper wrapper = new FNS_ObjectFieldSetWrapper.FNS_ObjectWrapper();
        wrapper.fields = FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c',fieldSetName);
        wrapper.moreFields = FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c',fieldSetName);
        wrapper.objectName = 'FNS_Collateral__c';
        wrapper.requiredFields = FNS_CollateralDomain.getFieldsFromFieldSet('FNS_Collateral__c',fieldSetName);
        wrapper.objectLabel = 'COLLATERAL';
        system.debug('wrapper>>>>'+wrapper);
        return wrapper; 
    }
        
    @AuraEnabled
    public static FNS_CollateralWrapper createCollateralsWithChildRecs(String collateralJson){
        //String collateralJson ='{"collateral":{"FNS_CollateralType__c":"Base_Collateral","FNS_Application__c":"0062E00001EhWL8QAN","FNS_Description__c":"Test","FNS_PledgedDate__c":"07/10/2019","FNS_PurchasedDate__c":"07/11/2019","FNS_ValueFairMarket__c":"200","FNS_ValueDate__c":"100","FNS_ValueSource__c":"07/20/2019","FNS_AppraisalDate__c":"06/22/2019"},"address":{"FNS_Street2__c":"Mariot Hotels","FNS_Street__c":"5th Avenue","FNS_City__c":"Delaware","FNS_PostalCode__c":"11111","FNS_State__c":"DE","FNS_CountryCode__c":"53237"}}';
        system.debug('@@@ collateralJson :: ' + collateralJson);
        FNS_CollateralWrapper wrapper = new FNS_CollateralWrapper();
        wrapper.isSuccess = true;
        system.debug('### createCollateralsWithChildRecs');
        try{
            List<String> collObj = collateralJson.split('\\}');
            String collateralJsonToConvert = '{' + (collObj[0].substringAfterLast('{')) + '}';
            String addressJson = '{' + (collObj[1].substringAfter('{')) + '}';
                
            Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(collateralJson);
            System.debug('@@ test ' + jsonMap);
            String documentId = String.valueOf(jsonMap.get('document')) ;
            system.debug('@@ documentId :: ' + documentId);
            sObject collateralObj = FNS_ProductWizardController.parseSOjects('FNS_Collateral__c', collateralJsonToConvert);
            insert collateralObj;
                
            sObject addressObj = FNS_ProductWizardController.parseSOjects('FNS_Address__c', addressJson);
            addressObj.put('FNS_Collateral__c',collateralObj.id );
            addressObj.put('FNS_Address1__c','tyty');
            insert addressObj;
            
            String prodIDs = String.valueOf(jsonMap.get('ProductIdSet')) ;
            if(prodIDs != null){
                List<String> prodIdList = prodIDs.split(',');
                List<FNS_CollateralWithProduct__c> collateralProdList = new List<FNS_CollateralWithProduct__c>();
                for(String prdId : prodIdList){
                    FNS_CollateralWithProduct__c prodObj = new FNS_CollateralWithProduct__c();
                    prodObj.FNS_Product__c = prdId;
                    prodObj.FNS_Collateral__c = collateralObj.id;
                    collateralProdList.add(prodObj);
                }
                insert collateralProdList;
            }
                
            if(documentId != null){
                FNS_CollateralDocument__c collDocObj = new FNS_CollateralDocument__c();
                collDocObj.FNS_Collateral__c = collateralObj.id;
                collDocObj.FNS_DocumentId__c = documentId;
                insert collDocObj;
            }
            wrapper.collateral = collateralObj;
            system.debug('### createCollateralsWithChildRecs 33 ');
        }catch(DMLException ex){
            logger.addLogRecord('FNS_CollateralCmpController', 'createCollateralsWithChildRecs', ex.getMessage() + ex.getStackTraceString());
            wrapper.errorMsg=ex.getMessage();
            wrapper.isSuccess = false;
        } catch (Exception ex){
            logger.addLogRecord('FNS_CollateralCmpController', 'createCollateralsWithChildRecs', ex.getMessage() + ex.getStackTraceString());
            wrapper.errorMsg=ex.getMessage();
            wrapper.isSuccess = false;
        }
        return wrapper;
    }
    
    @AuraEnabled
    public static List<sObject> getAllColaterals(){
        List<sObject> colletralList = [SELECT id,FNS_CollateralType__c,FNS_CollateralCategory__c FROM FNS_Collateral__c];
        //string collateralJson = JSON.serialize(colletralList);
        //return collateralJson;
        return colletralList;
    }

    @AuraEnabled
    public static List<FNS_CollateralWithDocumentsWrapper> getCollateralsByApplicationId(String applicationId){
        //sObject wrapper = new Sobject();
        List<FNS_CollateralWithDocumentsWrapper> collateralWrapper = new List<FNS_CollateralWithDocumentsWrapper>();
        List<FNS_CollateralWithProduct__c> collateralProductList = (List<FNS_CollateralWithProduct__c>) (new FNS_CollateralWithProductSelector().getCollateralsByApplicationId(applicationId));
        Set<String> collateralIdSet = new Set<String>();
        Map<String, String> categoryPickListMap = getPickListOptionsMap('FNS_Collateral__c', 'FNS_CollateralCategory__c');
        Map<String, String> collTypePickListMap = getPickListOptionsMap('FNS_Collateral__c', 'FNS_CollateralType__c');
        string documentName = '';
        for (FNS_CollateralWithProduct__c collateralProduct : collateralProductList) {
            if(collateralProduct.Id != null) {  
                System.Debug('>>>collateralProduct.Id>>>:'+collateralProduct.Id);
                List<FNS_CollateralDocument__c> collDocs = new FNS_CollateralDocumentSelector().getRecordsByCollateralId(collateralProduct.FNS_Collateral__c);
                FNS_CollateralWithDocumentsWrapper collWrapper = new FNS_CollateralWithDocumentsWrapper(collateralProduct, collDocs);
                collWrapper.collateralCatName = categoryPickListMap.get(collateralProduct.FNS_Collateral__r.FNS_CollateralCategory__c);
                collWrapper.collateralTypeName = collTypePickListMap.get(collateralProduct.FNS_Collateral__r.FNS_CollateralType__c); 
                collateralWrapper.add(collWrapper); 
            }                        
        }
        return collateralWrapper;
    }

    @AuraEnabled
    public Static List<sObject> getProductsByApplication(String applicationId){
        Map<String,String> prodNameIDMap = new Map<String,String>();
        List<sObject> productRecList = new FNS_ProductsSelector().selectApplicationProductWithChilds(new Set<ID>{ApplicationId});
        if(productRecList != null && !productRecList.isEmpty()) {
            for(Sobject productObj : productRecList) {
                prodNameIDMap.put(String.valueOf(productObj.get('Id')), String.valueOf(productObj.get('FNS_ProductSummary__c')));
            }
        }
        return productRecList;
    }

	public static Map<String, String> getPickListOptionsMap(String objApiName, String picklistApiName){
		Map<String, String> pickListOptionsMap = new Map<String, String>();
		Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get(objApiName).getDescribe().fields.getMap().get(picklistApiName).getDescribe();
        List<Schema.PicklistEntry> pleList = fieldResult.getPicklistValues();        
        for( Schema.PicklistEntry f : pleList){
            pickListOptionsMap.put(f.getValue(), f.getLabel());
        }
		return pickListOptionsMap;
	}
    
    public with sharing class FNS_CollateralWithDocumentsWrapper {
        @AuraEnabled public sObject Collateral {get; set;}
        @AuraEnabled public List<FNS_CollateralDocument__c> CollateralDocuments {get; set;} 
        @AuraEnabled public String collateralTypeName {get; set;}
        @AuraEnabled public String collateralCatName{get; set;}
        
        public FNS_CollateralWithDocumentsWrapper(sObject collateral, List<FNS_CollateralDocument__c> collateralDocuments) {
            this.Collateral = collateral;
            this.CollateralDocuments = collateralDocuments;
        }
    }

    public with sharing class FNS_CollateralWrapper {
            @AuraEnabled public Boolean isSuccess{get;set;}
            @AuraEnabled public String errorMsg{get;set;}
            @AuraEnabled public sObject collateral{get;set;}
    }
}