force-app/main/default/objects/FNS_ConfigurationType__c/FNS_ConfigurationType__c.object-meta.xml
<CustomObject>
    <label>Configuration Type</label>
    <nameField>
        <label>Configuration Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_ConfigurationType__c/fields/FNS_ConfigurationType__c.field-meta.xml
<CustomField>
    <fullName>FNS_ConfigurationType__c</fullName>
    <label>Configuration Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FNS_RelatedRoles__c/FNS_RelatedRoles__c.object-meta.xml
<CustomObject>
    <label>Application Roles</label>
    <nameField>
        <label>Application Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FNS_RelatedRoles__c/fields/FNS_AccountName__c.field-meta.xml
<CustomField>
    <fullName>FNS_AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>ApplicationAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_RelatedRoles__c/fields/FNS_Application__c.field-meta.xml
<CustomField>
    <fullName>FNS_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applications</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_RelatedRoles__c/fields/FNS_Contact__c.field-meta.xml
<CustomField>
    <fullName>FNS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ApplicationContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FNS_RelatedRoles__c/fields/FNS_RoleOfEntity__c.field-meta.xml
<CustomField>
    <fullName>FNS_RoleOfEntity__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Grantor</fullName>
            </value>            
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FNS_Contact__c.field-meta.xml
<CustomField>
    <fullName>FNS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Application (Contact)</relationshipLabel>
    <relationshipName>Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FNS_LeadTriggerHandler.cls
/************************************************************************************
* Copyright (c) 2019, Brillio
* All rights reserved.
* @author Brillio
* @date 2019
* @group Application
* @description This is for Application Trigger Handler
****************************************************************************************/
public with sharing class FNS_LeadTriggerHandler extends fflib_SObjectDomain {
    
    public static FNS_ErrorLog logger = new FNS_ErrorLog();
    
    public FNS_LeadTriggerHandler(List<FNS_ConfigurationType__c> sObjectList) {
        super(sObjectList);
    }
    
    /***********************************************************************************
* @description Constructor
* @Params      List<SObject>
* @Returns    fflib_SObjectDomain
***********************************************************************************/
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new FNS_LeadTriggerHandler(sObjectList);
        }
    }
    
    /***********************************************************************************
* @description method to run on Before Insert
* @Params      null
* @Returns    null
***********************************************************************************/
    public override void onBeforeInsert() {
    }
    /***********************************************************************************
* @description method to run on Before Update 
* @Params      Map
* @Returns    null
***********************************************************************************/
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords) {
        
    }
    
    /***********************************************************************************
* @description method to run on After Insert 
* @Params      null
* @Returns    null
***********************************************************************************/
    public override void onAfterInsert(){
        
    }
    
    /***********************************************************************************
* @description method to run on After Update
* @Params      Map 
* @Returns    null
***********************************************************************************/
    public override void onAfterUpdate(Map<Id,SObject> existingRecords) { 
        Set<Id> contactToCreateCommUser = new Set<Id>();
        List<Lead> leadList = trigger.new;
        system.debug('&&& leadList ' + leadList);
        Map<Id,Id> oppToContactMap = new Map<Id,Id>();
        Map<Id,Id> oppToAccountMap = new Map<Id,Id>();
        for (Lead lead:  leadList){
            if(lead.isconverted){
                contactToCreateCommUser.add(lead.ConvertedContactId);
                oppToContactMap.put((Id)lead.ConvertedOpportunityId,(Id)lead.ConvertedContactId);
                oppToAccountMap.put((Id)lead.ConvertedOpportunityId,(Id)lead.ConvertedAccountId);
            }
        }
        if(contactToCreateCommUser != null){
            new FNS_CommunityUtil().createCommunityUserFromContact(contactToCreateCommUser);
        }
        
        System.debug('@@ Oppmap ' + oppToContactMap);
        if(oppToContactMap != null && !oppToContactMap.isEmpty() ){
            populateContactOnApplication(oppToContactMap);
        }
        if(oppToContactMap != null && !oppToAccountMap.isEmpty() ){
	        populateApplicationRoleOnApplication(oppToAccountMap);
        }
    }
    
    Public void populateContactOnApplication(Map<Id,Id> oppToContactMap){
        List<Opportunity> oppList = new FNS_ApplicationSelector().selectApplicationById(oppToContactMap.keySet());
        System.debug('## oppList :: '  + oppList);
        for(Opportunity opp : oppList){
            opp.FNS_Contact__c = oppToContactMap.get(opp.id);
        }
        if(!oppList.isEmpty()){
            new FNS_ApplicationService().updateRecords(oppList);
        }
    }
    
    Public void populateApplicationRoleOnApplication(Map<Id,Id> oppToAccountMap){
        List<FNS_RelatedRoles__c> appRolesList = new List<FNS_RelatedRoles__c>();
        for(Id oppId : oppToAccountMap.keySet()){
            FNS_RelatedRoles__c appRole = new FNS_RelatedRoles__c();
            appRole.FNS_Application__c = oppId;
            appRole.FNS_AccountName__c = oppToAccountMap.get(oppId);
            appRole.FNS_RoleOfEntity__c = FNS_Constants.BORROWER;
            appRolesList.add(appRole);
        }
        if(!appRolesList.isEmpty()){
            new FNS_ApplicationRoleService().upsertRecords(appRolesList);
        }
    }
    
}